### ISSUE TITLE
Several problems with Ubuntu 14.04 (CMake 2.8.12) with latest YCM

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#106]
Saw them in the wild, now investigating them: 
 * `cmake_parse_arguments` not found: workaround by removing the dummy `CMakeParseArguments.cmake` modules from CMake >= 3.5 backported in YCM. 
* Something about a file not installed, investigating now.

**Comment by traversaro** [comment]
The second problem is the one that you get as soon as you try to run cmake on ycm repo master :+1:  
~~~
-- YCM Version: 0.2.1.3-20161125.2+git1769c22 (0.2.1.3)
CMake Error at cmake-next/CMakeLists.txt:184 (file):
  file COPY cannot find "/home/viki/ycm/cmake-next/v3.1/FindPkgConfig.cmake".


-- Downloading file Modules/CMakePackageConfigHelpers.cmake from CMake git repository (ref v3.1.3)
~~~

I wonder why Travis is not catching this.

**Comment by traversaro** [comment]
Probably the problem is that on Travis we pass `-DYCM_MAINTAINER_MODE=ON`.

**Comment by drdanz** [comment]
How is this possible, I spent one afternoon fixing CMakeParseArguments`on Ubuntu 14.04! It is supposed to copy the version in the v3.4.3 folder in all the folders where it is needed, can you check which one is wrong?

**Comment by traversaro** [comment]
Mhh, I am unable to reproduce the first issue after fixing the second one. Closing.
