### ISSUE TITLE
Add FindOpenNI2.cmake module

### ISSUE THREAD

**Issue by drdanz** [robotology/ycm#110]
YARP uses OpenNI2 to build the `depthCamera` module, but instead of having a `FindOpenNI2.cmake`, it is searched manually in the [`CMakeLists.txt`](https://github.com/robotology/yarp/blob/6434a40fd812a80fd58510a702661cad30ee5a02/src/devices/depthCamera/CMakeLists.txt#L6) file.

On Debian/Ubuntu there is a pkg-config file for it, therefore `StandardFindModule` can be used to create it.

**Comment by giuliavezzani** [comment]
I'm working in order to fix this issue.
I would create the `FindOpenNI2.cmake` file with the `StandardFindModule`. 
In  [**ycm** repo](https://github.com/robotology/ycm), where should I generate the `FindOpenNI2.cmake` file?

**Comment by drdanz** [comment]
@giuliavezzani Sorry for the delay, I missed this comment.
As I already wrote on the PR on YARP, the right place for new CMake modules is YCM (`devel` branch), we can copy it in YARP later.

**Comment by drdanz** [comment]
Yes, thanks!
