### ISSUE TITLE
gitlab downtime broke all the YCM-superbuilds in the world 

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#113]
Like it happened in https://github.com/robotology/ycm/issues/103 .

**Comment by traversaro** [comment]
Actually is not a change in the URL, is just a downtime in Gitlab due to https://about.gitlab.com/2017/02/01/gitlab-dot-com-database-incident/ . Closing once Gitlab is again up.

**Comment by traversaro** [comment]
cc @gabrielenava

**Comment by traversaro** [comment]
To anyone having the same problem: use the offline version of ycm available at https://github.com/robotology/ycm/releases .

**Comment by gabrielenava** [comment]
I received the error message in https://github.com/robotology/ycm/issues/103 while I was trying to build codyco-superbuild. I circumvented the problem editing this [CMakeLists.txt](https://github.com/robotology/ycm/blob/master/3rdparty/CMakeLists.txt) as follows:

ORIGINAL:

```
    set(_files LICENSE.txt                 8624bcdae55baeef00cd11d5dfcfa60f68710a02
               cmake/FindQCustomPlot.cmake a59dd4d955a5e775270a4f2656a039ae490e03ed)
    set(_ref 8689fcb1fdd2e8dc748e76d54d3b77a3f87d384c)
    set(_dir "${CMAKE_CURRENT_BINARY_DIR}/ovito")

```

HACKED:

```
    set(_files LICENSE.txt                 d67fc8b86209db26c338184aaa00e60572045d7d
               cmake/FindQCustomPlot.cmake d67fc8b86209db26c338184aaa00e60572045d7d)
    set(_ref 8689fcb1fdd2e8dc748e76d54d3b77a3f87d384c)
    set(_dir "${CMAKE_CURRENT_BINARY_DIR}/ovito")
```

**Comment by traversaro** [comment]
The Gitlab downtime is now solved, closing the issue (even if https://github.com/robotology/ycm/issues/105 remains open).
