### ISSUE TITLE
Drop FindEigen3.cmake in favour of Eigen3Config.cmake

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#120]
The `FindEigen3.cmake` provided upstream in Eigen3 has several issues, that are addressed by this PR: 
https://bitbucket.org/eigen/eigen/pull-requests/281/improve-findeigen3cmake/diff .

I recently discovered a new issue in  `FindEigen3.cmake` (see https://github.com/robotology/idyntree/pull/354), but given the lack of interest upstream in fixing the problems in `FindEigen3.cmake` I think it would be difficult to get integrated upstream. Given that Eigen3 provides its own `Eigen3Config.cmake` file now so eventually the `FindEigen3.cmake` will be unused, I am wondering if we could ship our own FindEigen3.cmake module in YCM instead of downloading the upstream one.

**Comment by traversaro** [comment]
As correctly pointed out by https://github.com/robotology/idyntree/pull/354#issuecomment-325296603 , if we assume we are targeting systems with Eigen3 version >= 3.2.92 , we can start using directly `find_package(Eigen3 CONFIG)` so we can ignore any `FindEigen3.cmake` logic.

**Comment by drdanz** [comment]
@traversaro which version of eigen3 is available in distributions listed in http://wiki.icub.org/wiki/YARP_Supported_Distributions and on brew for MacOS? Which version are we distributing in our windows package?

**Comment by traversaro** [comment]
Table in http://wiki.icub.org/wiki/YARP_Supported_Distributions updated. If we enable the bacports on Jessie, we can require Eigen 3.2.92 .

**Comment by drdanz** [comment]
What about windows packages?

**Comment by traversaro** [comment]
There  is now easy place to check the version without installing the installer, but it is Eigen 3.3.0 .

**Comment by traversaro** [comment]
I checked, the version in the installer is indeed 3.3.0 : 
~~~
#define EIGEN_WORLD_VERSION 3
#define EIGEN_MAJOR_VERSION 3
#define EIGEN_MINOR_VERSION 0
~~~
the problem is that the installer contains no `Eigen3Config.cmake` . I think this was due to the fact that the `Eigen3Config.cmake` produced by the installation procedure in Eigen 3.3.0 was not relocatable (see http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1347). This problem is now solved in the latest version of Eigen, but this means that we can't get rid of the `FindEigen3.cmake` file until we produce a new Windows installer after fixing the instructions for packaging Eigen3 (that I think are contained in the packaging VM and are not in any public repository).

**Comment by drdanz** [comment]
@traversaro Is this still an issue? All the releases we support have Eigen 3.3.2 or later

**Comment by traversaro** [comment]
Unfortunately yes. Our own installers install Eigen3 without installing an Eigen3Config.cmake (see https://github.com/robotology/icub-packaging/issues/8). Clearly fixing that issue would be highly preferable, as it would solve several related problems in a lot of libraries, see https://github.com/robotology/osqp-eigen/pull/19#issuecomment-460623261 .

**Comment by claudiofantacci** [comment]
So we will need to ship FindEigen3 with YCM, or am I wrong?
Just want to understand this and if I can help 😄

**Comment by drdanz** [comment]
If the windows packaging is the only issue, I'd rather fix that...

**Comment by claudiofantacci** [comment]
I totally agree! 👍

**Comment by traversaro** [comment]
I totally agree as well.

**Comment by drdanz** [comment]
Since we all agree, I'll close this as wontfix

**Comment by traversaro** [comment]
We should still drop the FindEigen3.cmake that we currently install with YCM, right?

**Comment by drdanz** [comment]
Yes, but IIRC, the `FindEigen3.cmake` looks for `EigenConfig`, therefore I suppose that we can remove it quietly as soon as the packaging is fixed.
Anyway I'll reopen and rename this issue.

**Comment by traversaro** [comment]
> 
> 
> Yes, but IIRC, the `FindEigen3.cmake` looks for `EigenConfig`, therefore I suppose that we can remove it quietly as soon as the packaging is fixed.
> Anyway I'll reopen and rename this issue.

The Windows binary dependencies provided by https://github.com/robotology/robotology-superbuild-dependencies-vcpkg now install correctly the `Eigen3Config.cmake` , so we may go ahead and remove the  `FindEigen3.cmake` from the next YCM superbuild release.

**Comment by traversaro** [comment]
This would avoid problems such as https://github.com/robotology/robotology-superbuild/issues/896 . 

Furthermore, we now stopped using the windows binaries generated by the scripts in https://github.com/robotology/icub-packaging in favor of vcpkg-provided binaries https://github.com/robotology/robotology-superbuild-dependencies-vcpkg and conda-forge-provided ones, so I think there should be no problem in dropping FindEigen3.cmake in the next YCM release.

**Comment by traversaro** [comment]
@drdanz feel free to let me know if just deleting FindEigen3 is ok (in that case I would go with the PR) or if you prefer to have some sort of deprecation.

**Comment by PeterBowman** [comment]
Related: https://github.com/robotology/ycm/issues/387.

**Comment by drdanz** [comment]
Is the Eigen3Config fixed anywhere? Are the targets the same?
If that's the case, I think we can just delete it without deprecation, as it is just no longer needed.
