### ISSUE TITLE
YCM installation fails on brew

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/ycm#121]
Hi,
It seems like YCM can't be installed using brew, see e.g. https://travis-ci.org/robotology/icub-main/jobs/274533299
It would be great if this could be fixed, as this currently breaks all tests on OS X with YCM / Yarp as dependency.

Best,
Tobi

**Comment by drdanz** [comment]
cc @francesco-romano

**Comment by francesco-romano** [comment]
I don't think it is YCM which is failing, but this command (executed after the installation of YCM which instead is successful)

`"if [ \"$TRAVIS_OS_NAME\" = \"osx\" ]; then brew install `brew deps --1 yarp | sed -e ':a' -e 'N' -e '$!ba' -e 's/\\n/ /g'`; fi",`

Honestly, I don't know who wrote that command and why.

**Comment by francesco-romano** [comment]
cc @traversaro

**Comment by francesco-romano** [comment]
Issue opened in cub-main: https://github.com/robotology/icub-main/issues/470
closing this.
