### ISSUE TITLE
AUTHOR_WARNINGs that depend on CMAKE_MINIMUM_REQUIRED_VERSION on the downstream project

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#136]
I am setting up a ycm-based superbuild that with CMAKE_MINIMUM_REQUIRED_VERSION equal to 3.5, and I am getting a lot of AUTHOR_WARNING such as https://github.com/robotology/ycm/blob/331f21737df560e9a484c4ceb4f1398fe8ca2e14/modules/StandardFindModule.cmake#L104 . 
As correctly pointed out in 
https://github.com/robotology/ycm/pull/76#issuecomment-65210965 , all this warnings should be checking the `CMAKE_MINIMUM_REQUIRED_VERSION` used by YCM, not the one of the downstream project.

**Comment by drdanz** [comment]
I think this should be fixed in `devel`
