### ISSUE TITLE
Use FetchContent for bootstrap phase

### ISSUE THREAD

**Issue by drdanz** [robotology/ycm#138]
We should test if it is possible to use [`FetchContent`](https://cmake.org/cmake/help/latest/module/FetchContent.html) instead of YCM bootstrap phase.
Also we should check if the FetchContent module can be used with previous CMake version and if we can import it in cmake-next

**Comment by traversaro** [comment]
> Also we should check if the FetchContent module can be used with previous CMake version and if we can import it in cmake-next

In gazebo-fmi, we vendor the `FetchContent` module and it is working fine (tested by Travis) on Xenial (CMake 3.5), see https://github.com/robotology/gazebo-fmi/pull/23 .

**Comment by drdanz** [comment]
`FetchContent` imported in latest `devel` (b195e0d1dbc89f542cbad38f2a58e86625c6c525)

**Comment by drdanz** [comment]
An experiment with robotology-superbuild was done here: robotology/robotology-superbuild#473 (see also the comments).
