### ISSUE TITLE
AppVeyor is failing due to maximum allowed artifact storage size exceed

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#141]
The actual error message is:
> Maximum allowed artifact storage size of 50000 Mb will be exceeded.

See https://ci.appveyor.com/project/robotology/ycm/build/job/a5qwcvrkgy6x6u8q .

**Comment by drdanz** [comment]
As a temporary solution, I manually deleted lots of old builds...
I wonder if there is a way to delete them automatically.
Also I would be happy to enable artifacts only for tags, I don't know if there is a way...

**Comment by drdanz** [comment]
I also restarted the builds for your PR...

**Comment by drdanz** [comment]
Still failing :(
I'm merging the PR anyway

**Comment by drdanz** [comment]
I temporarily disabled the artifacts...
We should find a way to fix it before next release

**Comment by drdanz** [comment]
This is still an issue, honestly I cannot understand why this is happening since appveyor retention policy should now be operative

**Comment by claudiofantacci** [comment]
@drdanz do you have a link to a failed test becuase of this issue?

**Comment by drdanz** [comment]
https://ci.appveyor.com/project/robotology/ycm/builds/20612970

**Comment by claudiofantacci** [comment]
That is really strange...I would try removing the artifacts line altogether.

**Comment by drdanz** [comment]
This is currently disabled. Closing this.
