### ISSUE TITLE
Probable RPATH error

### ISSUE THREAD

**Issue by diegoferigo** [robotology/ycm#147]
Coming from https://github.com/robotology/idyntree/issues/441#issuecomment-390148540 and https://github.com/robotology/idyntree/issues/241, on my system (Ubuntu 16:04) I realized that not only the python bindings have RPATH problems. All of our built libraries I checked have a sort of RPATH enabled, but an absolute path is prepended.

E.g. in yarp:

```
dferigo@8d5539413fc2:/iit/local/lib> ldd libYARP_math.so
        linux-vdso.so.1 =>  (0x00007ffe664e5000)
        libYARP_sig.so.1 => /iit/local/lib/./libYARP_sig.so.1 (0x00007fa2cfa86000)
        libYARP_OS.so.1 => /iit/local/lib/./libYARP_OS.so.1 (0x00007fa2cf66c000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa2cf2ea000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa2cefe1000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa2cedcb000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa2cea01000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa2ce7e4000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa2ce5e0000)
        libedit.so.2 => /usr/lib/x86_64-linux-gnu/libedit.so.2 (0x00007fa2ce3a8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa2d0037000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fa2ce17f000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fa2cdf6a000)
```

I'm not an expert and to be honest I still struggle to understand in depth RPATH. I would have expected not to see the `/iit/local/lib` prefix.

cc @claudiofantacci @drdanz @traversaro @francesco-romano 

All `*SKIP_INSTALL_RPATH*` variables are set to `OFF`. This happens also with other libraries, e.g. iDynTree.

**Comment by claudiofantacci** [comment]
> In Linux when you ldd it shows the full path (with or without RPATH).

😲 I didn't remember/know that. Thanks @francesco-romano 👍

**Comment by francesco-romano** [comment]
Well... let's say that I am sure at 99%.. I can't test it now :D

**Comment by drdanz** [comment]
try `objdump -x libYARP_math.so | grep -2 PATH` (it will match both `RPATH` and `RUNPATH` since this changed for some reason). This will show the actual RPATH... For the installation it should be something like
```
RUNPATH              $ORIGIN/:$ORIGIN/../lib:$ORIGIN/../
```

**Comment by claudiofantacci** [comment]
Kitware has a new Wiki page under their GitLab website and they updated the documentation concerning [RPATH](https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/RPATH-handling).

I was unaware of `RUNPATH` before checking this issue with @diegoferigo, beware that **`RPATH` is ignored if RUNPATH is present.**

**Comment by diegoferigo** [comment]
@francesco-romano No I didn't try to move the folder. This is a very limited use-case since it need also changing some of the environment variables of the system.

> In Linux when you ldd it shows the full path

Strange behavior :sweat_smile: Thanks to have shed some light on it.

@drdanz `objdump` work fine, good to know!

```
dferigo@999b1522505b:/iit/local/lib> objdump -x libYARP_math.so | grep -2 PATH
  NEEDED               libc.so.6
  SONAME               libYARP_math.so.3
  RPATH                $ORIGIN/:$ORIGIN/../lib:$ORIGIN/../
  INIT                 0x0000000000008000
  FINI                 0x00000000000b6128
```

In the end this was the right behavior, at least we (for sure I) learned something new :tada:

**Comment by traversaro** [comment]
>  Kitware has a new Wiki page under their GitLab website and they updated the documentation concerning [RPATH](https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/RPATH-handling).

I think it is the best explanation of RPATH I ever seen. We should link it whenever we discuss about rpath support (such as the in the C++ libraries howto).

**Comment by claudiofantacci** [comment]
> I think it is the best explanation of RPATH I ever seen.

Well, yes I think that as well, but still for experienced user who understand the importance of the _install name_ recorded in the library etc. To be honest I find that the description made by @francesco-romano in the YCM module [AddInstallRPATHSupport.cmake](https://github.com/robotology/ycm/blob/master/modules/AddInstallRPATHSupport.cmake) is also very informative.

> We should link it whenever we discuss about rpath support (such as the in the C++ libraries howto).

Yes and considering the above considerations I would also point to/copy-paste/re-elaborate and use the description of [AddInstallRPATHSupport.cmake](https://github.com/robotology/ycm/blob/master/modules/AddInstallRPATHSupport.cmake).

**Comment by francesco-romano** [comment]
@diegoferigo which variables are you referring to?
Technically, only the `PATH` variable should be updated (and unfortunately `YARP_DATA_DIRS` until we found a smarter solution)

**Comment by diegoferigo** [comment]
@francesco-romano Unfortunately `LD_LIBRARY_PATH` is stil required in particular cases. See https://github.com/robotology/robotology-superbuild/pull/82 as a reference.

**Comment by francesco-romano** [comment]
ah yes.. modules might still need to be located on the file system
