### ISSUE TITLE
Incomplete sentence in AddInstallRPATHSupport doc

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/ycm#151]
The following statement is incomplete

https://github.com/robotology/ycm/blob/11f45a366fee3e0f35d847c7cfaa601cc5b9687d/modules/AddInstallRPATHSupport.cmake#L50-L51

@francesco-romano, I can take care of it, but can you please suggest me how to complete it?

I would suggest something like this:
`In all cases (building executables and/or shared libraries) dependent shared libraries with RPATH support will have their name resolved only at run time.`

**Comment by francesco-romano** [comment]
wow. You are right. 
I don't know why the sentence is incomplete.

I would also change the line 32-33 in the active form:
```
# RPATH aims in solving the issues introduced by the second
# installation method.
```

For the incomplete sentence, I think your completion is ok, but I would add also that the search path will be embedded in the binary itself. Something like
```
In all cases (building executables and/or shared libraries) dependent shared libraries with RPATH support will have their name resolved only at run time, by embedding the search path directly into the built binary.
```

**Comment by claudiofantacci** [comment]
I'll change the file right away from here.
