### ISSUE TITLE
In a YCM superbuild, CMAKE_GENERATOR_PLATFORM is not propagated correctly to subproject

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#177]
If I configure a superbuild as: 
~~~
cmake -G "Visual Studio 15 2017" -A x64 ...
~~~

The subprojects will use the Win32 (i.e. x86 32-bit) platform generator, instead of the x64 (i.e. amd64 64-bit).

Everything works fine (the subprojects build for 64-bit) if I use the old-style generators names: 
~~~
cmake -G "Visual Studio 15 2017 Win64" ..
~~~ 

I guess that his related to the fact that YCM uses an outdated ExternalProject fork, for which for example this commit is missing: :https://gitlab.kitware.com/cmake/cmake/commit/6944997bd6aa69fdf88f8e4e154e68d57195b20b .

**Comment by traversaro** [comment]
Related to https://github.com/robotology/ycm/issues/50 .

**Comment by drdanz** [comment]
@traversaro Is this fixed by #188?

**Comment by traversaro** [comment]
Yes.

**Comment by traversaro** [comment]
@Nicogene you had a related problem, right?
