### ISSUE TITLE
make install

### ISSUE THREAD

**Issue by drdanz** [robotology/ycm#18]
Figure out how to handle "make install" in superprojects

**Comment by drdanz** [comment]
An option could be to configure projects with the right `CMAKE_INSTALL_PREFIX` and install them in the "install phase" using `DESTDIR="${CMAKE_BINARY_DIR}/install" make install`.
In this way it should be possible to use `make install` without `DESTDIR` to perform the real installation.

A minor issue will be that all the paths will change from ``${CMAKE_BINARY_DIR}/install`` to ``${CMAKE_BINARY_DIR}/install/${CMAKE_INSTALL_PREFIX}``

**Comment by traversaro** [comment]
I must say that in modifying the "install" directory from `${CMAKE_BINARY_DIR}/install` to `${CMAKE_BINARY_DIR}/install/${CMAKE_INSTALL_PREFIX}` would be a bit problematic in existing superbuilds. The superbuild is already an explosion of different directories that can be difficult for the users to get, installing stuff in `${CMAKE_BINARY_DIR}/install/usr/local` by default would complicate things even more.

**Comment by drdanz** [comment]
Agreed... Nonetheless it's the only method that I could find until now that will work with cmake and autotools.
We could eventually use a link

**Comment by drdanz** [comment]
Another possible solution would be to use `install(CODE)`, adding the actual install command. This would work with any install command.
The problem is that this would break the current workflow because installation would happen only in the `make install` phase.
Also it would require some trick to force the projects to find the relative dependencies, that are not installed during the `make` phase. Perhaps the trick with `DESTDIR` in [this comment](https://github.com/robotology/ycm/issues/18#issuecomment-121604936) could work.

**Comment by drdanz** [comment]
Fixed in #235
