### ISSUE TITLE
Understand  if it is necessary to expose the new ARCH_INDIPENDENT parameter in InstallBasicPackageFiles

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#185]
See https://gitlab.kitware.com/cmake/cmake/merge_requests/2666 .

**Comment by drdanz** [comment]
It should be quite easy to expose it, but we should check if unknown parameters are just ignored by  `write_basic_package_version_file`, otherwise we have to import the latest version of `CMakePackageConfigHelpers` and related files as well...

**Comment by drdanz** [comment]
Fixed in #187
