### ISSUE TITLE
[YCMEPHelper] Add new argument for GIT: folder name

### ISSUE THREAD

**Issue by EnricoMingo** [robotology/ycm#191]
Hi, this is a suggestion: should be nice to have the possibility to optionally specify the nome of the folder for the git clone. This is very easy in git:

```git clone repo_url folder_name```

**Comment by liesrock** [comment]
Should be already possible with the <name> arg (https://github.com/robotology/ycm/blob/3b628e2d4757dd1291d87b9829da6b17955e1964/modules/YCMEPHelper.cmake)

**Comment by EnricoMingo** [comment]
Which one?

**Comment by liesrock** [comment]
If you check the link it is the first argument of the function (called <name>)

**Comment by EnricoMingo** [comment]
Sorry, I can not find it:

```

#  ycm_ep_helper(<name>
#    [DOCS]
#    [TYPE <type>]
#    [STYLE <style>]
#    [COMPONENT <component>] (default = "external")
#    [FOLDER <folder> (default = "<component>")
#    [REPOSITORY <repo>]
#    [EXCLUDE_FROM_ALL <0|1>]
#   #--Git and Hg only arguments-----------
#    [TAG <tag>]
#   #--Svn only arguments-----------
#    [REVISION <revision>]
#    [USERNAME <username>]
#    [PASSWORD <password>]
#    [TRUST_CERT <0|1>]
#   #--CMake arguments---------
#    [CMAKE_ARGS]
#    [CMAKE_CACHE_ARGS]
#    [CMAKE_CACHE_DEFAULT_ARGS]
#    [DEPENDS]
#    [DOWNLOAD_COMMAND]
#    [UPDATE_COMMAND]
#    [PATCH_COMMAND]
#    [CONFIGURE_COMMAND]
#    [BUILD_COMMAND]
#    [INSTALL_COMMAND]
#    [TEST_COMMAND]
#    [CLEAN_COMMAND] (not in ExternalProject)
#    [TEST_AFTER_INSTALL]
#    [TEST_BEFORE_INSTALL]
#    [TEST_EXCLUDE_FROM_MAIN]
#    )
```

maybe the ```FOLDER``` param?

**Comment by liesrock** [comment]
The fist J

ycm_ep_helper(<name>

That name

**Comment by EnricoMingo** [comment]
Ok, got it, so the ```<name>``` is also used for the folder, I thought it was just used for the CMakeLists, ok then I'll close.

**Comment by liesrock** [comment]
Sorry I got now why you were not seeing it: I was writing it with the < > angular parenthesis on my phone: it is the first arg called name
