### ISSUE TITLE
option "install with rpath" would be useful

### ISSUE THREAD

**Issue by elen4** [robotology/ycm#2]
this option appears (with different name, and maybe different behaviour, I haven't checked) in both yarp and icub repositories

**Comment by drdanz** [comment]
@elen4 @francesco-romano do you think I can close this, or is something still missing? We have the [AddInstallRPATHSupport](https://github.com/robotology/ycm/blob/master/modules/AddInstallRPATHSupport.cmake) module now...

**Comment by francesco-romano** [comment]
From the OS X side I think the basic functionalities are ready.
For problems we can always open new issues.

**Comment by drdanz** [comment]
Ok, thanks! Closing this.

**Comment by francesco-romano** [comment]
CMake 3.9 is out.
Given the changes in https://cmake.org/cmake/help/v3.9/policy/CMP0068.html#policy:CMP0068
we should update our RPATH macro

**Comment by drdanz** [comment]
Yes, thanks
