### ISSUE TITLE
set(YCM_USE_CMAKE_PROPOSED ON) does not work at the first CMake execution

### ISSUE THREAD

**Issue by drdanz** [robotology/ycm#212]
Continuing discussion from #210

**Comment by drdanz** [comment]
@PeterBowman wrote:

I'm a bit baffled by how CMake treats local vs cached variables. I'm following [this example](http://robotology.github.io/ycm/gh-pages/git-master/manual/ycm-superbuild-example.7.html#superbuild-example-developer-point-of-view) regarding the required (for my use case) `YCM_USE_CMAKE_PROPOSED` var. In short, it boils down to:

```cmake
set(YCM_USE_CMAKE_PROPOSED ON)
include(YCMBootstrap)
include(FindOrBuildPackage)
# do stuff, i.e. request Buildorocos_kdl.cmake
```

Relevant lines on the YCM side:

https://github.com/robotology/ycm/blob/1a231f296f859b4e476707fd655e5c5df7c98ce4/YCMConfig.cmake.in#L44-L48

This code is not taking into account the proposed module path after the first configure execution. My `set(YCM_USE_CMAKE_PROPOSED ON)` instruction only takes effect on the second run and onwards, which might have misled me in my previous experiments.

Can anyone reproduce this behaviour? Should the linked documentation be updated?

**Comment by drdanz** [comment]
@drdanz wrote

Hmm I think you are right. I tested this with every CMake version since 2.8.7:

```cmake
cmake_minimum_required(VERSION 2.8.7)
project(test_cmake_option NONE)

set(FOO ON)
option(FOO "Foo" OFF)

set(BAR ON)
set(BAR OFF CACHE BOOL "Bar")

message("FOO = ${FOO}")
message("BAR = ${BAR}")
```

The output is always `OFF` the first time and `ON` the second. I don't know if this was different in previous CMake versions, but 2.8.7 is old enough to let me think that that this never worked on the first execution.

Anyway, in my opinion the real problem is the documentation, but the fact that `YCM_USE_CMAKE_PROPOSED` is cached... See also #57 (`YCM_USE_CMAKE_PROPOSED` was probably added after opening that issue, therefore it is not listed there).

**Comment by drdanz** [comment]
@PeterBowman wrote

Hmm I think you are right. I tested this with every CMake version since 2.8.7:

```cmake
cmake_minimum_required(VERSION 2.8.7)
project(test_cmake_option NONE)

set(FOO ON)
option(FOO "Foo" OFF)

set(BAR ON)
set(BAR OFF CACHE BOOL "Bar")

message("FOO = ${FOO}")
message("BAR = ${BAR}")
```

The output is always `OFF` the first time and `ON` the second. I don't know if this was different in previous CMake versions, but 2.8.7 is old enough to let me think that that this never worked on the first execution.

Anyway, in my opinion the real problem is the documentation, but the fact that `YCM_USE_CMAKE_PROPOSED` is cached... See also #57 (`YCM_USE_CMAKE_PROPOSED` was probably added after opening that issue, therefore it is not listed there).

**Comment by drdanz** [comment]
I think that at the very beginning, I was using `FORCE` as well, at least for the other variables, but for some reason I changed it. Anyway, until these variables are no longer cached, that's the right way to do it

**Comment by claudiofantacci** [comment]
I'm also facing this issue and I report that if I use `set(YCM_USE_CMAKE_PROPOSED ON)`, either before or after `find_package(YCM)`, the first CMake pass ignore the variable, while the second uses it _even though_ the GUI does not report it as enabled.

I think that hte CMake behaviour is explained in policy [CMP0077](https://cmake.org/cmake/help/latest/policy/CMP0077.html#policy:CMP0077).

**Comment by drdanz** [comment]
Fixed by #220

**Comment by drdanz** [comment]
@PeterBowman Please let me know if you still have issues with this.

**Comment by PeterBowman** [comment]
> @PeterBowman Please let me know if you still have issues with this.

I confirm that the *local* way to do this (`set(YCM_USE_CMAKE_PROPOSED ON)`) now works, indeed. Thanks!
