### ISSUE TITLE
Wrong behaviour of InstallBasicPackageFile when using CMake older than 3.9

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/ycm#216]
_Originally posted by @giuliavezzani in https://github.com/robotology/superquadric-lib/issues/18#issuecomment-471959585_

I fixed the problem in [this commit](5aa536dd9c517c9fd428f005877f27d112df8ccf).
There was an undesired behavior in the [InstallBasicPackageFile.cmake](https://github.com/robotology/superquadric-lib/commit/5aa536dd9c517c9fd428f005877f27d112df8ccf#diff-1ea7d7a4904962c0ca3ab99a5738f67a) for my `cmake version`.

I added @jchevrie's suggestion (`DEPENDENCIES "VTK 8.1 REQUIRED" Eigen3`) and now the export for VTK with the correct version works fine also for me. :+1: @jchevrie 

Thanks to @claudiofantacci.

cc @drdanz

**Comment by claudiofantacci** [comment]
[This is the diff](https://github.com/robotology/superquadric-lib/commit/5aa536dd9c517c9fd428f005877f27d112df8ccf#diff-1ea7d7a4904962c0ca3ab99a5738f67a) that fixed the problem.

If you have CMake version 3.9 or less (e.g. 3.5.1 in Xenial) and you call `InstallBasicPackageFile` passing a string to the `DEPENDENCIES` option (e.g. "VTK 8.1"), the generated config file turns out to be malformed because instead of generating `find_package(VTK 8.1 ${VARIABLE_IF_REQUIRED} ${VARIABLE_IF_QUIET})` provides `find_package(VTK ${VARIABLE_IF_REQUIRED} ${VARIABLE_IF_QUIET} 8.1)`.

The above-mentioned fix works well, but I'm not sure whether it is just a workaround or not. Anyway, we should address this issue.

**Comment by claudiofantacci** [comment]
I'd like to work on this.
I'm making a change in the file and open a PR.

**Comment by drdanz** [comment]
> I'd like to work on this.
:heart:

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/ycm/pull/238 ?

**Comment by claudiofantacci** [comment]
Absolutely. Thanks @traversaro!

Closing 🚀
