### ISSUE TITLE
Find modules overriding CMake ones

### ISSUE THREAD

**Issue by drdanz** [robotology/ycm#222]
The following modules override CMake modules:

* [ ] FindGLUT.cmake (Available in CMake 3.5)
* [ ] FindGSL.cmake (Available in CMake 3.5)
* [ ] FindOpenGL.cmake (Available in CMake 3.5, targets and other features in newer releases)
* [x] FindQt3.cmake (hopefully no longer used anywhere)

I think we should get rid of these, or move them in the proposed section if they have features missing in CMake

---

Edit:

* [ ] FindOctave.cmake (Not available in CMake 3.14, but we should make it compatible with the module proposed upstream, see also #193, #196 and [CMake#18988](https://gitlab.kitware.com/cmake/cmake/issues/18988))

**Comment by claudiofantacci** [comment]
Totally agree.

My two cents on
 - `FindGLUT`: the latest version seems really good and suitable for Windows. I think we can get rid of it here.
 - `FindOpenGL`: get it from the latest release or from CMake 3.10+. It has some nice targets, including nice ones for Linux.
 - `FindQt3`: lolwut? 🗑

**Comment by drdanz** [comment]
We should check that the variables have the same names though (even though I hope that we can just get rid of `FindQt3`

Since we are doing this, we could also consider adding to `FindOctave.cmake` the same variables/targets as in the upstream [`FindOctave.cmake`](https://gitlab.kitware.com/cmake/cmake/blob/e6897c72e7c59f7a0b82ed19c1bdb40d42f7adaa/Modules/FindOctave.cmake) that was temporarily removed, but will be added again in the future. See also #193, #196 and [CMake#18988](https://gitlab.kitware.com/cmake/cmake/issues/18988)

**Comment by drdanz** [comment]
`FindQt3` deprecated, if someone is still using it, it is time to switch to Qt5
