### ISSUE TITLE
Superbuild dependencies in YCM v0.10.1 use build instead of install dir

### ISSUE THREAD

**Issue by PeterBowman** [robotology/ycm#244]
Tested on [roboticslab-uc3m/asibot-main](https://github.com/roboticslab-uc3m/asibot-main/tree/0259f65fb5c7043319ca0f8d0cc212f15d171b09), a superbuild-like project. Let's focus on the [ROBOTICSLAB_KINEMATICS_DYNAMICS subproject](https://github.com/roboticslab-uc3m/asibot-main/blob/0259f65fb5c7043319ca0f8d0cc212f15d171b09/cmake/ycm-modules/BuildROBOTICSLAB_KINEMATICS_DYNAMICS.cmake), which depends on [COLOR_DEBUG](https://github.com/roboticslab-uc3m/asibot-main/blob/0259f65fb5c7043319ca0f8d0cc212f15d171b09/cmake/ycm-modules/BuildCOLOR_DEBUG.cmake) and [orocos_kdl](https://github.com/roboticslab-uc3m/asibot-main/blob/0259f65fb5c7043319ca0f8d0cc212f15d171b09/cmake/ycm-modules/Buildorocos_kdl.cmake) (among others), and assume we have successfully configured this superbuild project and compiled said dependencies. Next, if we try to build ROBOTICSLAB_KINEMATICS_DYNAMICS, [Travis CI reports an error](https://travis-ci.org/roboticslab-uc3m/asibot-main/jobs/516983168#L9780) due to a missing inclusion:

`/home/travis/build/roboticslab-uc3m/asibot-main/external/ROBOTICSLAB_KINEMATICS_DYNAMICS/libraries/KdlVectorConverterLib/KdlVectorConverter.hpp:8:26: fatal error: kdl/frames.hpp: No such file or directory`

The KdlVectorConverterLib component depends on orocos_kdl (which in turn depends on Eigen3) and COLOR_DEBUG, so let's check the C++ include flags specified in the *flags.make* CMake-generated file at `build/external/ROBOTICSLAB_KINEMATICS_DYNAMICS/libraries/KdlV
ectorConverterLib/CMakeFiles/KdlVectorConverterLib.dir/`:

```
CXX_INCLUDES = \
  -I/root/git/asibot-main/build/external/orocos_kdl/../../../include \
  -I/usr/include/eigen3 \
  -I/root/git/asibot-main/external/ROBOTICSLAB_KINEMATICS_DYNAMICS/libraries/KdlVectorConverterLib \
  -isystem /root/git/asibot-main/external/COLOR_DEBUG 
```

And, now, compare its contents when YCM v0.9.1 is used, instead:

```
CXX_INCLUDES = 
  -I/root/git/asibot-main/build/install/share/orocos_kdl/cmake/../../../include \
  -I/usr/include/eigen3 \
  -I/root/git/asibot-main/external/ROBOTICSLAB_KINEMATICS_DYNAMICS/libraries/KdlVectorConverterLib \
  -isystem /root/git/asibot-main/build/install/include 
```

It seems to me that YCM v0.10.1 is looking for orocos_kdl's and COLOR_DEBUG's include directories in the **build tree** (`root/external/`), whereas YCM v0.9.1 was using the intermediate local **install tree** (`root/build/install/`). This is easier to spot in the COLOR_DEBUG case. In fact, orocos_kdl is known to not be prepared for being consumed by dependent projects without a prior install step (the usual `<...>_DIR` approach), hence its resulting include paths are bogus. Nevertheless, I find it strange that `build/install/` is not used anymore and might be considered a regression.

**Comment by traversaro** [comment]
Can you copy&paste (even in a gist) the `CMakeCache.txt` of the superbuild and of the `KdlVectorConverterLib` subproject? Thanks.

**Comment by traversaro** [comment]
It would be great to also get the CMake invocation command that configures the `KdlVectorConverterLib` lib.

**Comment by PeterBowman** [comment]
YCM v0.10.1: [superbuild CMakeCache.txt](https://github.com/robotology/ycm/files/3055262/CMakeCache.txt), [ROBOTICSLAB_KINEMATICS_DYNAMICS CMakeCache.txt](https://github.com/robotology/ycm/files/3055290/CMakeCache.txt).

YCM v0.9.1: [superbuild CMakeCache.txt](https://github.com/robotology/ycm/files/3055263/CMakeCache.txt), [ROBOTICSLAB_KINEMATICS_DYNAMICS CMakeCache.txt](https://github.com/robotology/ycm/files/3055291/CMakeCache.txt).

> It would be great to also get the CMake invocation command that configures the `KdlVectorConverterLib` lib.

I'm not sure what you mean, please note that `KdlVectorConverterLib` is a library target defined in the `ROBOTICSLAB_KINEMATICS_DYNAMICS` subproject of the `asibot-main` superbuild repository (it's a mess, sorry). Where should I look at? We don't pass any additional CMake options in the fetch&configure step ([Buildxxx.cmake file](https://github.com/roboticslab-uc3m/asibot-main/blob/0259f65fb5c7043319ca0f8d0cc212f15d171b09/cmake/ycm-modules/BuildROBOTICSLAB_KINEMATICS_DYNAMICS.cmake)).

**Comment by traversaro** [comment]
> I'm not sure what you mean, please note that `KdlVectorConverterLib` is a library target defined in the `ROBOTICSLAB_KINEMATICS_DYNAMICS` subproject of the `asibot-main` superbuild repository (it's a mess, sorry). Where should I look at? We don't pass any additional CMake options in the fetch&configure step ([Buildxxx.cmake file](https://github.com/roboticslab-uc3m/asibot-main/blob/0259f65fb5c7043319ca0f8d0cc212f15d171b09/cmake/ycm-modules/BuildROBOTICSLAB_KINEMATICS_DYNAMICS.cmake)).

Sorry, then I meant the cmake configure of `ROBOTICSLAB_KINEMATICS_DYNAMICS` subproject . I guess it should be sufficient to run `VERBOSE=1 make ROBOTICSLAB_KINEMATICS_DYNAMICS`, and it should be printed just after the `Performing configure step for 'ROBOTICSLAB_KINEMATICS_DYNAMICS'` (save the output to a file and search if afterwards if it is too verbose).

**Comment by PeterBowman** [comment]
Thanks, that would be `/root/git/asibot-main/build/external/ROBOTICSLAB_KINEMATICS_DYNAMICS/CMakeFiles/YCMTmp/ROBOTICSLAB_KINEMATICS_DYNAMICS-cache-.cmake` (for future reference). It's quite small, I'm copy-pasting its contents here:

```cmake
set(CMAKE_INSTALL_PREFIX "/root/git/asibot-main/build/install" CACHE PATH "Initial cache" FORCE)
set(CMAKE_BUILD_TYPE "" CACHE STRING "Initial cache" )
set(CMAKE_SKIP_RPATH "NO" CACHE PATH "Initial cache" )
set(CMAKE_SKIP_INSTALL_RPATH "NO" CACHE PATH "Initial cache" )
```

With YCM v0.9.1:

```cmake
set(CMAKE_INSTALL_PREFIX "/root/git/asibot-main/build2/install" CACHE PATH "Initial cache" FORCE)
set(CMAKE_BUILD_TYPE "" CACHE STRING "Initial cache" FORCE)
set(CMAKE_SKIP_RPATH "NO" CACHE PATH "Initial cache" FORCE)
set(CMAKE_SKIP_INSTALL_RPATH "NO" CACHE PATH "Initial cache" FORCE)
```

**Comment by PeterBowman** [comment]
I compared `build/external/*/CMakeCache.txt` for YCM v0.9.x and v0.10.x. The former sets `CMAKE_PREFIX_PATH` to `build/install`, whereas this variable remains unset in the latter case.

**Comment by PeterBowman** [comment]
**YCM v0.9.1**

https://github.com/robotology/ycm/blob/b1f002f0fd7a0d48288abc5cf0d39c4c5a54ba76/modules/YCMEPHelper.cmake#L783-L792

The `build/install/` directory is appended to `_CMAKE_PREFIX_PATH` at line 784 and further set as a CLI option in `${_name}_YCM_CMAKE_ARGS`:

https://github.com/robotology/ycm/blob/b1f002f0fd7a0d48288abc5cf0d39c4c5a54ba76/modules/YCMEPHelper.cmake#L812-L816

**YCM v0.10.1**

https://github.com/robotology/ycm/blob/8eed406a684764bfd5ddd1ff06db1bb6a7e19ece/modules/YCMEPHelper.cmake#L235-L237

`_CMAKE_PREFIX_PATH` is empty.

https://github.com/robotology/ycm/blob/8eed406a684764bfd5ddd1ff06db1bb6a7e19ece/modules/YCMEPHelper.cmake#L826-L830

At this point, `_CMAKE_PREFIX_PATH` contains the expected installation paths (even better, since new YCM prepends them to existing ones). However, this is not reflected in the options passed through CLI and we get an empty `-DCMAKE_PREFIX_PATH:PATH=` as explainer earlier:

https://github.com/robotology/ycm/blob/8eed406a684764bfd5ddd1ff06db1bb6a7e19ece/modules/YCMEPHelper.cmake#L832-L836

Idea: either restore the old location of the `set(_YCM_EP_CMAKE_ARGS ...)` line or move the `file(TO_CMAKE_PATH ...)` block *before* that line. Offending change: https://github.com/robotology/ycm/commit/4f9d1d45304f2797476896c3400bc3117fcffe72 (https://github.com/robotology/ycm/pull/231).

**Comment by PeterBowman** [comment]
>  or move the `file(TO_CMAKE_PATH ...)` block _before_ that line.

See https://github.com/robotology/ycm/pull/246.
