### ISSUE TITLE
Disable YCMEPHelper install target

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#252]
For a long time, YCM-based superbuild did not have any `install` target. For several reasons, it may be convenient to avoid generating an `install` target. @drdanz do you think it could make sense to have something like an option/variable to toggle this? 

cc @Giulero @gabrielenava

**Comment by drdanz** [comment]
To be honest, I'm against this... Having people trying the install, even if it does not work, means more bug reports to the subprojects, and in the end, an improvement to the overall code quality.

**Comment by traversaro** [comment]
The  main problem (at least regarding the robotology-superbuild) is that the `install` target needs to be properly documented, added support for it in the configuration scripts, add an uninstall target, and finally the users need to be educated on its use. I am happy to eventually do that, but in the transition period it is less error prone for users to just avoid to generate the `install` target, as especially new users are (unfortunately) used to blindly do `cmake .`/`make`/`sudo make install` when  dealing with CMake projects. 

However `YCMEPHelper` is already a configuration monster, so I see the point for avoiding having yet another configuration switch for it.

**Comment by drdanz** [comment]
I think you can disable the `install` target in your project by just doing something like this before including any subproject:

```cmake
macro(install)
endmacro()
```

**Comment by traversaro** [comment]
Ack, I agree, it does not make sense to add further complexity to `YCMEpHelper` .

**Comment by traversaro** [comment]
> 
> 
> To be honest, I'm against this... Having people trying the install, even if it does not work, means more bug reports to the subprojects, and in the end, an improvement to the overall code quality.

Just to clarify: the main problem of this option is that a superbuild will find its owns installed project, as in the case of `YCM_EP_INSTALL_DIR`, see https://github.com/robotology/ycm/pull/289 and the discussion in https://github.com/robotology/robotology-superbuild/pull/316 . As in that case, probably it would make sense that the `install` target should only be used for compile and install once superbuilds.
