### ISSUE TITLE
Latest YCM devel of robotology-superbuild on Travis with Docker blocks during bootstrap on "Performing build step for 'YCM''

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#254]
See https://travis-ci.org/robotology/robotology-superbuild/builds/527715806 . Until yesterday, everything went fine. I already restarted a job, and the same problem appeared again. 

I wonder if the problem is related to this commit: https://github.com/robotology/ycm/commit/912e0d6f9ac5d54b3206f31c152eaa84e121893c

**Comment by traversaro** [comment]
Apparently the problem is there also with v0.10.2 (see https://travis-ci.org/robotology/robotology-superbuild/builds/527850737?utm_source=github_status&utm_medium=notification), so the problem is probably some weird Travis problem in accessing one of the remote repos used in the YCM bootstrap (ref https://github.com/robotology/ycm/issues/105).

**Comment by traversaro** [comment]
I am unable to reproduce the problem on my local machine.

**Comment by traversaro** [comment]
I enabled `YCM_BOOSTRAP_VERBOSE` in a test build (https://github.com/robotology/robotology-superbuild/pull/201) and apparently the problem is some strange interaction of CMake's git repo and Travis. The line
~~~
 [ 16%] Downloading file Copyright.txt from CMake git repository (ref v3.14.3)
~~~
took ~2/3 minutes, and now the build seems stuck to:
~~~
[ 17%] Downloading file Modules/BasicConfigVersion-SameMajorVersion.cmake.in from CMake git repository (ref v3.14.3)
~~~
see https://travis-ci.org/robotology/robotology-superbuild/jobs/527863239 .

**Comment by traversaro** [comment]
Related tweets: 
* https://twitter.com/SleevelessZach/status/1124323582337867777
* https://twitter.com/beaugunderson/status/1124336607333535745

**Comment by beaugunderson** [comment]
i'm in contact with travis support and will let y'all know if i hear anything useful from them :)

**Comment by traversaro** [comment]
I tried  replicating the issue on ycm's Travis, but apparently everything is working correctly there. Probably the issue is related to the fact the the robotology-superbuild Travis build is working inside a docker container.

**Comment by traversaro** [comment]
> i'm in contact with travis support and will let y'all know if i hear anything useful from them :)

Thanks a lot @beaugunderson !

**Comment by beaugunderson** [comment]
if you want to contact their support as well you can reference our support ticket so they can cross-reference it; it's 6994

**Comment by zak10** [comment]
I'm not familiar at all with this repository, but my builds have also been getting stuck and timing out. Strangely, it happens during different stages and it is only for one of my repositories. I reran builds from old commits that were fine and those are also breaking so assuming this is a travis problem.

Running a python 3.6 container, tests via docker compose.

**Comment by beaugunderson** [comment]
fwiw we also use docker/docker-compose in our tests...

**Comment by zak10** [comment]
@beaugunderson do your tests run in multiple threads?

**Comment by beaugunderson** [comment]
@zak10 yup, we use gnu `parallel`

**Comment by alex** [comment]
I'm also experiencing this issue -- also in docker builds.

**Comment by zak10** [comment]
We're using pytest + xdist to run tests in parallel. I'm attempting now to remove xdist completely to see if that alleviates the issue.

**Comment by beaugunderson** [comment]
still no response from travis since last thursday :(

**Comment by beaugunderson** [comment]
currently trying to force `dist: xenial` and see if that has any effect, will report back...

**Comment by beaugunderson** [comment]
> Hi Beau,
> 
> Thank you for getting in touch, and we apologize for the frustration caused by this ongoing issue with slow or stalling downloads from within Docker containers.
> 
> We’ve been receiving similar reports since late on Friday and have proceeded to open an incident to acknowledge the situation here: https://www.traviscistatus.com/incidents/kyf149kl6bvp. We'll be posting updates to the status as we continue to investigate this issue.
> 
> In the meantime, you might be able to stabilize your builds and prevent having to manually restart them by adding travis_retry to your failing commands e.g.
> 
> travis_retry docker build [...]
> 
> This will effectively retry the command up to 3 times if it fails.
> 
> Once again we apologize for the inconvenience caused as we work diligently towards a resolution. In the meantime, if you have any questions or concerns, please do not hesitate to get in touch. We'd be happy to assist.

**Comment by beaugunderson** [comment]
i feel like this fundamentally misunderstands the issue, sadly

**Comment by beaugunderson** [comment]
`dist: xenial` did not help, FYI

**Comment by zak10** [comment]
yep - got the same canned response from them. at least they're acknowledging the issue now. unfortunately for them, I've already begun the process of migrating to Circle.

best of luck!

**Comment by traversaro** [comment]
I tried the `--network=host` workaround mentioned in https://www.traviscistatus.com/incidents/kyf149kl6bvp in https://travis-ci.org/robotology/robotology-superbuild/jobs/528940445, and it seems to be working.

**Comment by beaugunderson** [comment]
awesome @traversaro; i'm trying that now as well (slightly more complicated with docker-compose, but it seems like `network_mode: ${NETWORK_MODE:-bridge}` inside the `build:` option would work, and then specifying `NETWORK_MODE=host` for travis builds

**Comment by beaugunderson** [comment]
this is more of a pain than i thought, especially if you already use `networks`...

**Comment by traversaro** [comment]
Related issue: https://github.com/ros-industrial/industrial_ci/issues/364 .

**Comment by beaugunderson** [comment]
travis is claiming that this issue is fixed but we're still getting 100% failures... around the time they were testing fixes we got a few passes, so it certainly improved for a small period of time, but now it's broken again and i'm having a hard time getting their support to do anything about it

**Comment by traversaro** [comment]
On our side, in the last day all the build that were affected by that (see https://travis-ci.org/robotology/robotology-superbuild/jobs/529722072) are working correctly. Given @beaugunderson input, probably it make sense to monitor a bit more for possible failures.

**Comment by traversaro** [comment]
On our side, we did not observed Travis failures related to this in the past week. I think we can close the issue, at least for what concern YCM and its bootstrap.
