### ISSUE TITLE
UseSWIG module requires CMake 3.14+

### ISSUE THREAD

**Issue by PeterBowman** [robotology/ycm#256]
Commit https://github.com/robotology/ycm/commit/d8fc9ff7611aa6a8f4e159ca746268812e097a25 started fetching UseSWIG.cmake module from CMake 3.14.4 (was 3.8.2). This module requires CMake 3.14+, see [these lines](https://github.com/Kitware/CMake/blob/v3.14.4/Modules/UseSWIG.cmake#L237-L240) ([CMP0078](https://cmake.org/cmake/help/v3.14/policy/CMP0078.html) and [CMP0086](https://cmake.org/cmake/help/v3.14/policy/CMP0086.html) were introduced in CMake 3.13 and 3.14, respectively). Affects YCM 0.10.3.

Related: https://github.com/robotology/ycm/issues/248. Cannot apply same solution (provide own YCM version of this module) easily because of those two CMake policy declarations, modern generator expressions (https://github.com/Kitware/CMake/commit/88dd5dc9ff405ee5bd63b15ea1e5219e5d029e12) and a major rework that requires CMake 3.11 (https://github.com/Kitware/CMake/commit/0bef9eb410566aa10536331d086d4a3ee265a526).

**Comment by drdanz** [comment]
@PeterBowman Should be fixed in master, can you please let me know if you still have issues?
I also added a few unit tests to test that cmake-next and 3rd party files can be at least included, it should avoid a few of these issues...

**Comment by PeterBowman** [comment]
Hi, @drdanz. Looks good, thanks, but CMake keeps finding the "old" (upstream) UseSWIG.cmake. I think the patched local version gets overwritten in the download step, so this line should be removed:

https://github.com/robotology/ycm/blob/6056bae91c34ad78608b05e1790562de07855195/cmake-next/CMakeLists.txt#L287

**Comment by drdanz** [comment]
Sorry, I forgot about that, I don't know why I didn't have any issue. It should be working now...

**Comment by PeterBowman** [comment]
This module still requires a recent version of CMake. I'm trying to configure latest YARP devel with `-DYARP_COMPILE_BINDINGS=ON -DCREATE_PYTHON=ON`, these errors show up:

```
CMake Error at /usr/local/share/YCM/cmake-3.14/Modules/UseSWIG.cmake:710 (list):
  list does not recognize sub-command JOIN
Call Stack (most recent call first):
  bindings/python/CMakeLists.txt:36 (swig_add_library)


CMake Error at /usr/local/share/YCM/cmake-3.14/Modules/UseSWIG.cmake:857 (message):
  Cannot find Swig library "yarp_python".
Call Stack (most recent call first):
  bindings/python/CMakeLists.txt:39 (swig_link_libraries)


CMake Error at bindings/python/CMakeLists.txt:40 (target_include_directories):
  Cannot specify include directories for target "SYSTEM" which is not built
  by this project.


CMake Error at bindings/python/CMakeLists.txt:66 (get_target_property):
  get_target_property called with incorrect number of arguments
```

Perhaps only the first error is meaningful, `list(JOIN)` was added in CMake 3.12 ([docs](https://cmake.org/cmake/help/v3.12/command/list.html)).

**Comment by drdanz** [comment]
This time it was quite hard! :rofl: 
It should be fixed for real this time

**Comment by PeterBowman** [comment]
Almost there, CMake does not complain anymore :). Generation seems broken, though:

```
$ make yarp_python_swig_compilation
[100%] COMMAND_EXPAND_LISTS
/bin/sh: 1: Syntax error: ";;" unexpected
bindings/python/CMakeFiles/yarp_python_swig_compilation.dir/build.make:61: recipe for target 'bindings/python/CMakeFiles/_yarp_python.dir/yarpPYTHON.stamp' failed
make[3]: *** [bindings/python/CMakeFiles/_yarp_python.dir/yarpPYTHON.stamp] Error 2
make[3]: *** Deleting file 'bindings/python/CMakeFiles/_yarp_python.dir/yarpPYTHON.stamp'
CMakeFiles/Makefile2:6412: recipe for target 'bindings/python/CMakeFiles/yarp_python_swig_compilation.dir/all' failed
make[2]: *** [bindings/python/CMakeFiles/yarp_python_swig_compilation.dir/all] Error 2
CMakeFiles/Makefile2:6419: recipe for target 'bindings/python/CMakeFiles/yarp_python_swig_compilation.dir/rule' failed
make[1]: *** [bindings/python/CMakeFiles/yarp_python_swig_compilation.dir/rule] Error 2
Makefile:1484: recipe for target 'yarp_python_swig_compilation' failed
make: *** [yarp_python_swig_compilation] Error 2
```

**Comment by drdanz** [comment]
Sorry, I cannot reproduce it with CMake 3.5.2...
Copying all the files in `<ycm_build_dir>/share/YCM/cmake-next/Modules` in `<yarp_source_dir>/cmake`:

```
$ /opt/cmake-3.5/bin/cmake .. -DYARP_COMPILE_BINDINGS=ON -DCREATE_PYTHON=ON && make _yarp_python
[...]
-- YARP Version: 3.1.101 (3.1.101+20190604.17+git577d6adf0+dirty)
[...]
-- Using:
--   CMake: 3.5.2 (/opt/cmake-3.5/bin/cmake)
--   C Compiler: GNU 8.3.0 (/usr/bin/cc)
--   CXX Compiler: GNU 8.3.0 (/usr/bin/c++)
[...]
--  [x] SWIG (>= 3.0): found 3.0.12 (/usr/share/swig3.0)
[...]
--  [x] Bindings (YARP_COMPILE_BINDINGS)
--  [ ]   Java bindings (CREATE_JAVA)
--  [x]   Python bindings (CREATE_PYTHON)
--  [ ]   Perl bindings (CREATE_PERL)
--  [ ]   CSharp bindings (CREATE_CSHARP)
--  [ ]   TCL bindings (CREATE_TCL)
--  [ ]   Ruby bindings (CREATE_RUBY)
--  [ ]   Lua bindings (CREATE_LUA)
--  [ ]   Octave bindings (CREATE_OCTAVE)
-- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable exact version "2.7.16") 
[...]
[100%] Swig source
[...]
Scanning dependencies of target _yarp_python
[100%] Building CXX object bindings/python/CMakeFiles/_yarp_python.dir/__/__/lib/python/yarpPYTHON_wrap.cxx.o
[100%] Linking CXX shared module ../../lib/python/_yarp.so
[100%] Built target _yarp_python
```

I don't have the `yarp_python_swig_compilation` target though, my target name is `_yarp_python`

**Comment by PeterBowman** [comment]
Thank you for your effort and patience :). This time it's a bit different, perhaps linked to some stray configuration (although I erased everything in the build dir):

```
[100%] Building CXX object bindings/python/CMakeFiles/_yarp_python.dir/__/__/lib/python/yarpPYTHON_wrap.cxx.o
/bin/sh: 1: cannot create -I/home/teo/repos/yarp/build/src/libYARP_conf/include: Directory nonexistent
bindings/python/CMakeFiles/_yarp_python.dir/build.make:62: recipe for target 'bindings/python/CMakeFiles/_yarp_python.dir/__/__/lib/python/yarpPYTHON_wrap.cxx.o' failed
make[2]: *** [bindings/python/CMakeFiles/_yarp_python.dir/__/__/lib/python/yarpPYTHON_wrap.cxx.o] Error 2
CMakeFiles/Makefile2:6336: recipe for target 'bindings/python/CMakeFiles/_yarp_python.dir/all' failed
make[1]: *** [bindings/python/CMakeFiles/_yarp_python.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

This is latest devel, Python 3.5.2 and SWIG 3.0.8. I'll try on another machine.

**Comment by drdanz** [comment]
can you please try with `VERBOSE=1 make yarp_python_swig_compilation` and post the command line as well?

**Comment by PeterBowman** [comment]
The `yarp_python_swig_compilation` target builds successfully, I'm unable to `make all`. Verbose output (the last few lines that show an error):

```
[100%] Building CXX object bindings/python/CMakeFiles/_yarp_python.dir/__/__/lib/python/yarpPYTHON_wrap.cxx.o
cd /home/teo/repos/yarp/build/bindings/python && /usr/bin/c++   -DBUILDING_YARP -D_yarp_python_EXPORTS -Dlib/python/yarpPYTHON_wrap.cxxTARGET_PROPERTY:_yarp_python,SWIG_GENERATED_COMPILE_DEFINITIONS> -I/home/teo/repos/yarp/build/src/libYARP_conf/include -I/home/teo/repos/yarp/src/libYARP_OS/include -I/home/teo/repos/yarp/src/libYARP_sig/include -I/home/teo/repos/yarp/src/libYARP_dev/include -isystem /usr/include/python3.5m -I/home/teo/repos/yarp/src/libYARP_dev/idl_generated_code/include  -w -Os -DNDEBUG -fPIC   -std=c++11 -o CMakeFiles/_yarp_python.dir/__/__/lib/python/yarpPYTHON_wrap.cxx.o -c /home/teo/repos/yarp/build/lib/python/yarpPYTHON_wrap.cxx
/bin/sh: 1: cannot create -I/home/teo/repos/yarp/build/src/libYARP_conf/include: Directory nonexistent
bindings/python/CMakeFiles/_yarp_python.dir/build.make:62: recipe for target 'bindings/python/CMakeFiles/_yarp_python.dir/__/__/lib/python/yarpPYTHON_wrap.cxx.o' failed
make[2]: *** [bindings/python/CMakeFiles/_yarp_python.dir/__/__/lib/python/yarpPYTHON_wrap.cxx.o] Error 2
make[2]: Leaving directory '/home/teo/repos/yarp/build'
CMakeFiles/Makefile2:6336: recipe for target 'bindings/python/CMakeFiles/_yarp_python.dir/all' failed
make[1]: *** [bindings/python/CMakeFiles/_yarp_python.dir/all] Error 2
make[1]: Leaving directory '/home/teo/repos/yarp/build'
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

That `Dlib/python/yarpPYTHON_wrap.cxxTARGET_PROPERTY:_yarp_python,SWIG_GENERATED_COMPILE_DEFINITIONS>` looks suspicious...

**Comment by PeterBowman** [comment]
In fact, this generator expression does not get expanded: [ref](https://github.com/robotology/ycm/blob/5dbda4df81a93545ee2036d02bcf79bd8194e5e9/cmake-next/v3.14.4/UseSWIG.cmake#L415). See [cmake-generator-expressions.7.html#string-transformations](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#string-transformations):

> `$<TARGET_GENEX_EVAL:tgt,expr>`
> This naive implementation of the `printFooKeys` custom command is wrong because `CUSTOM_KEYS` target property is not evaluated and the content is passed as is (i.e. `$<$<CONFIG:DEBUG>:FOO_EXTRA_THINGS>`).

**Comment by drdanz** [comment]
This time I managed to do a full YARP build. I have no idea how to support ``SWIG_GENERATED_INCLUDE_DIRECTORIES``, ``SWIG_GENERATED_COMPILE_DEFINITIONS`` and ``SWIG_GENERATED_COMPILE_OPTIONS`` though, therefore I disabled them in CMake < 3.12...
They are not used in YARP though

**Comment by drdanz** [comment]
@PeterBowman I'm planning to do yet another fix release tomorrow, please let me know if you still have issues

**Comment by PeterBowman** [comment]
@drdanz I can confirm it works now (YARP v3.1.1 and latest devel, CMake 3.5.1, Python 2.x and 3.x), thanks! Please mind https://github.com/robotology/yarp/issues/2037 upon importing YCM in YARP.
