### ISSUE TITLE
`install_basic_package_files()`: add `NO_EXPORT` option

### ISSUE THREAD

**Issue by mbeutel** [robotology/ycm#263]
`install_basic_package_files()` currently requires an export to be specified. However, sometimes we want to install but don't have an export set or any targets to export, e.g. in a CMake script library such as YCM itself.

Would you consider adding a `NO_EXPORT` option to `install_basic_package_files()` which makes it skip the `install()` and `export()` commands related to the export set? I'd be happy to provide a pull request.

**Comment by drdanz** [comment]
Looks useful, thanks for the suggestion. It would be great to see `InstallBasicPackageFiles` used in YCM itself.
If you want to provide a pull request I'll be happy to merge it.

**Comment by drdanz** [comment]
Merged, thanks! And thanks for adding the YCM installation part! :heart_eyes:

**Comment by drdanz** [comment]
Fixed by @mbeutel in #268
