### ISSUE TITLE
Exported build directories: check build configuration

### ISSUE THREAD

**Issue by mbeutel** [robotology/ycm#264]
When using `export(PACKAGE)` to export a build directory to the user package registry, CMake will find the exported build directory in `find_package()` calls of other packages. This is very convenient when simultaneously working on a library and on a project consuming the library.

CMake defines a mechanism for mapping build configurations for imported targets. This means that a project can be installed with more than one build configuration, and CMake will automatically select the configuration that matches your current build configuration. However, exported build directories for single-config generators (e.g. Ninja or Makefile) only contain a single build configuration, hence the mapping logic doesn't apply.

While it is possible to export multiple build directories with different build configurations to the package registry, this isn't particularly helpful; `find_package()` only matches target architecture and version semantics, and it simply picks the first match among the exported build directories. This usually goes unnoticed on non-Windows systems (GCC kind of tolerates mixing debug and release builds) but leads to linker errors with VC++ on Windows (VC++ doesn't support mixing debug and release builds). And these are hard to diagnose – why does CMake find the "wrong" build directory? – and hard to resolve: the only way to reliably enforce using a particular build configuration from an exported build directory is to erase the package registry entries for all other build directories.

(I'd argue that even on non-Windows platforms the behavior is broken because one shouldn't be mixing debug and non-debug builds, and that the linker errors in VC++ are actually a feature. libstdc++ doesn't mind if you mix object files with different settings for `_GLIBCXX_DEBUG`, but of course this switch changes object layouts, which is fun to debug.)

In my own projects I currently work around this problem by using a custom "...ConfigVersion.cmake" file which also matches the build configuration

- if the exported build directory uses a single-config generator,
- if the package is not "arch-independent",
- if the user didn't disable this behavior by defining `IGNORE_EXPORTED_BUILD_DIR_CONFIG`.

Note that I do this only for exported build directories; the version check in the installed package remains unaltered.

Code snippet:

```cmake
# ExtendedConfigVersion.cmake.in
...
# Build configurations are considered to match if both are "Debug" or neither
# is "Debug". All other configurations can be matched freely.
if(NOT "@_IBPF_ARCH_INDEPENDENT@"
   AND NOT "@GENERATOR_IS_MULTI_CONFIG@"
   AND NOT IGNORE_EXPORTED_BUILD_DIR_CONFIG)
    if(GENERATOR_IS_MULTI_CONFIG)
        set(PACKAGE_VERSION "${PACKAGE_VERSION} single-config")
        set(PACKAGE_VERSION_UNSUITABLE TRUE)
        return()
    elseif(("${CMAKE_BUILD_TYPE}" STREQUAL "Debug" AND NOT "@CMAKE_BUILD_TYPE@" STREQUAL "Debug")
           OR (NOT "${CMAKE_BUILD_TYPE}" STREQUAL "Debug" AND "@CMAKE_BUILD_TYPE@" STREQUAL "Debug"))
        set(PACKAGE_VERSION "${PACKAGE_VERSION} single-config CMAKE_BUILD_TYPE=@CMAKE_BUILD_TYPE@")
        set(PACKAGE_VERSION_UNSUITABLE TRUE)
        return()
    endif()
endif()
```

It's not perfect and not very friendly towards user-defined build configurations, but it's a start, and I think it is better than the current situation.

Is this something you would consider adding to YCM's `install_basic_package_files()`? I'd be happy to provide a pull request if desired.

**Comment by drdanz** [comment]
I agree that this could be a problem, but I'm not really sure that this should belong to `InstallBasicPackageFiles`...
The version handling is forwarded to the [`write_basic_package_version_file`](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html#command:write_basic_package_version_file) command from [`CMakePackageConfigHelpers`](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html).
Unfortunately, this module is not very configurable (it is possible to choose only one of the preset 4 `COMPATIBILITY` options).

I suggest to work upstream in CMake to improve `write_basic_package_version_file` and import the updated version in YCM, so that we can use it in `InstallBasicPackageFiles`.
I see 2 possible ways to fix it:
1. Fix the issue in each of the `COMPATIBILITY` templates
2. Modify the command to allow to pass a custom version template

(The changes are not mutually exclusive)

@mbeutel does this seem a reasonable way to fix the issue? Would you be happy to work upstream on this?

**Comment by mbeutel** [comment]
Of course this is just a workaround, not a proper solution.

True, `write_basic_package_version_file()` is not really configurable, hence what I currently do is to generate an unaltered version file with `write_basic_package_version_file()` with the desired `COMPATIBILITY` and `ARCH_INDEPENDENT` settings and then `include()` it in my wrapper file.

Because `install_basic_package_files()` doesn't offer the possibility to provide a custom version template, and, more importantly, because I think the change described here would be wanted in almost any case, I figured that the least impactful way to implement this would be to change `install_basic_package_files()` as described above. Of course we could instead extend `install_basic_package_files()` to permit custom version templates, but then every project that wants sane behavior for exported build directories has to do a lot of extra work to opt in.

Making this the default behavior is important for another reason: it is not the library that suffers from this problem, it is always the dependent project. To fix the issue with a custom version template when it occurs in a dependent project, it is the library project that needs to be changed.

---

Of course you are right this is a deeper issue which demands a solution in CMake itself. But I suspect that, from a CMake perspective, fiddling with the version compatibility templates wouldn't be the "right" solution. Perhaps it would be more appropriate to extend the package registry mechanism so it can distinguish between single-config and multi-config build directories. I don't know.

I'll try to get some feedback from CMake people on this.

**Comment by mbeutel** [comment]
Cf. https://gitlab.kitware.com/cmake/cmake/issues/19563

**Comment by mbeutel** [comment]
Feedback summary: this could be fixed on the CMake side, but the package registry was never designed to handle this, and `CMP0090` "effectively removes it by default".

So perhaps it's better to adjust my workflow to avoid the package registry entirely, and teach others accordingly.
