### ISSUE TITLE
AddInstallRPATHSupport: add option to completly disable rpath configuration

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#292]
In some configurations, having an option to completely disable the rpath configuration may be useful, see https://www.reddit.com/r/cpp/comments/dnc0n2/how_to_export_c_library_an_osagnostic_c_library/f5bditk/ for more context.

**Comment by drdanz** [comment]
IIRC, this is supported using [`CMAKE_SKIP_RPATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_SKIP_RPATH.html), [`CMAKE_SKIP_INSTALL_RPATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_SKIP_INSTALL_RPATH.html), and [`CMAKE_SKIP_BUILD_RPATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_SKIP_BUILD_RPATH.html)

**Comment by traversaro** [comment]
I may be wrong, but for all possible values of those libraries `CMAKE_INSTALL_NAME_DIR` is always modified in https://github.com/robotology/ycm/blob/master/modules/AddInstallRPATHSupport.cmake ?

**Comment by drdanz** [comment]
That's Apple only stuff, and if I remember correctly, it must be enabled, or there will be issues, see https://gitlab.kitware.com/cmake/cmake/issues/16589

**Comment by traversaro** [comment]
Ok, thanks for the info, I think we can close the issue then.
