### ISSUE TITLE
option "compile position independent code" could be useful

### ISSUE THREAD

**Issue by elen4** [robotology/ycm#3]
to enable fPIC option on gcc also when building static libraries, so that they can be linked by other shared libraries. I am not sure if/when this is useful, but as this behaviour (always compile PIC) is in place in the icub repository, we should "regulate" it

**Comment by drdanz** [comment]
CMake has the `CMAKE_POSITION_INDEPENDENT_CODE` variable and `POSITION_INDEPENDENT_CODE` property for this, This should be handled on a subproject level.
