### ISSUE TITLE
Could the default `INSTALL_DESTINATION` path be unified?

### ISSUE THREAD

**Issue by mbeutel** [robotology/ycm#305]
Currently `install_basic_package_files()` chooses a platform-dependent location for the CMake config file:

https://github.com/robotology/ycm/blob/bf613de66f2eb02751c8c0c863f32ea0afa173dd/modules/InstallBasicPackageFiles.cmake#L352..L360

```cmake
  # FIXME CMake 3.7 use the same path
  # FIXME Use ARCH_INDEPENDENT to choose destination
  if(NOT DEFINED _IBPF_INSTALL_DESTINATION)
    if(WIN32 AND NOT CYGWIN)
      set(_IBPF_INSTALL_DESTINATION CMake)
    else()
      set(_IBPF_INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${_Name})
    endif()
  endif()
```

This is presumably done to follow what the CMake documentation calls "Windows convention" and "Unix convention", cf. https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure.

However, CMake searches the prefixes listed in the documentation regardless of platform (cf. [source](https://gitlab.kitware.com/cmake/cmake/blob/master/Source/cmFindPackageCommand.cxx#L2103)); some subdirectories like "\<prefix\>/lib/\<arch\>/cmake/\<name\>\*/" or "\<prefix\>\/lib32/cmake/\<name\>\*/" are platform-specific, but most prefixes, and in particular "\<prefix\>/lib/cmake/\<name\>\*/" and "\<prefix\>/share/cmake/\<name\>\*/", are always searched. So making a distinction is unnecessary here as far as I can tell.

Having a platform-specific config file location causes additional complexity for [Vcpkg](https://github.com/Microsoft/vcpkg/) portfiles for packages that install with YCM's `install_basic_package_files()`. [Example](https://mp-force.ziti.uni-heidelberg.de/asc/infrastructure/vcpkg-ports/blob/master/vcpkg/ports/slowmath/portfile.cmake#L20):

```cmake
if(VCPKG_TARGET_IS_WINDOWS)
    vcpkg_fixup_cmake_targets(CONFIG_PATH "CMake" TARGET_PATH "share/<name>")
else()
    include(GNUInstallDirs) # for CMAKE_INSTALL_LIBDIR
    vcpkg_fixup_cmake_targets(CONFIG_PATH "${CMAKE_INSTALL_LIBDIR}/cmake/<name>" TARGET_PATH "share/<name>")
endif()
```

The following change to InstallBasicPackageFiles.cmake:

```diff
  if(NOT DEFINED _IBPF_INSTALL_DESTINATION)
-   if(WIN32 AND NOT CYGWIN)
-     set(_IBPF_INSTALL_DESTINATION CMake)
-   else()
      set(_IBPF_INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${_Name})
-   endif()
  endif()
```

would simplify the portfile to

```diff
include(GNUInstallDirs) # for CMAKE_INSTALL_LIBDIR
vcpkg_fixup_cmake_targets(CONFIG_PATH "${CMAKE_INSTALL_LIBDIR}/cmake/<name>" TARGET_PATH "share/<name>")
```

Perhaps the inline FIXME comment in https://github.com/robotology/ycm/blob/master/modules/InstallBasicPackageFiles.cmake#L352 had the same intention (although I don't understand the reference to CMake 3.7).

Is there any reason why YCM has platform-specific defaults for `INSTALL_DESTINATION`, other than to follow conventions?

If this is only for conventions, perhaps it is noteworthy that Vcpkg (originally a package manager for VC++ on Windows but ported to other platforms since) has established the convention of using "\<prefix\>/share/\<name\>\*/" regardless of platform.

**Comment by traversaro** [comment]
Short answer: now that YCM requires CMake 3.12, it totally make sense to do the change that you propose, so feel free to propose a PR with the modifications in the issue. 

Long answer: 

> Perhaps the inline FIXME comment in https://github.com/robotology/ycm/blob/master/modules/InstallBasicPackageFiles.cmake#L352 had the same intention (although I don't understand the reference to CMake 3.7).

Before 3.7, this double logic was necessary to make sure that, when using the default `CMAKE_INSTALL_PREFIX` value in Windows, the installed packages were found without further user intervention (such as setting the `CMAKE_PREFIX_PATH` or setting the `<pkg>_DIR` . You can find more details in the CMake issue https://gitlab.kitware.com/cmake/cmake/issues/16212 , and on the related MR https://gitlab.kitware.com/cmake/cmake/issues/18658 .

> If this is only for conventions, perhaps it is noteworthy that Vcpkg (originally a package manager for VC++ on Windows but ported to other platforms since) has established the convention of using "<prefix>/share/<name>*/" regardless of platform.

Unfortunately this "convention" is not compatible with other much older "conventions" of what should go in `share` for Unix systems, that is typically just architecture independent files, while CMake config files depend or not in the architecture if the library is header only or not. You can read more about this in: 
* https://github.com/microsoft/vcpkg/issues/77#issuecomment-255862551
* https://gitlab.kitware.com/cmake/cmake/merge_requests/2455#note_469969 
* https://gitlab.kitware.com/cmake/cmake/issues/18453

**Comment by mbeutel** [comment]
Thank you; these links clear up a lot of things.

So, following the guidance in https://gitlab.kitware.com/cmake/cmake/issues/18453#note_470670, I guess the following change would be appropriate:

```diff
-   # FIXME CMake 3.7 use the same path
-   # FIXME Use ARCH_INDEPENDENT to choose destination
    if(NOT DEFINED _IBPF_INSTALL_DESTINATION)
-     if(WIN32 AND NOT CYGWIN)
-       set(_IBPF_INSTALL_DESTINATION CMake)
+     if(_IBPF_ARCH_INDEPENDENT)
+       set(_IBPF_INSTALL_DESTINATION ${CMAKE_INSTALL_DATADIR}/cmake/${_Name})
      else()
        set(_IBPF_INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${_Name})
      endif()
    endif()
```

A corresponding Vcpkg portfile would then read either

```cmake
# for architecture-specific projects
include(GNUInstallDirs) # for CMAKE_INSTALL_LIBDIR
vcpkg_fixup_cmake_targets(CONFIG_PATH "${CMAKE_INSTALL_LIBDIR}/cmake/<name>" TARGET_PATH "share/<name>")
```

or

```cmake
# for architecture-independent projects
include(GNUInstallDirs) # for CMAKE_INSTALL_DATADIR
vcpkg_fixup_cmake_targets(CONFIG_PATH "${CMAKE_INSTALL_DATADIR}/cmake/<name>" TARGET_PATH "share/<name>")
```

Do you consider using `${CMAKE_INSTALL_DATADIR}` an unnecessary indirection, given that `find_package()` is specified to look in "\*/share/\*" and does not mention `DATADIR`?

I'll prepare a PR soon.

**Comment by traversaro** [comment]
> Do you consider using `${CMAKE_INSTALL_DATADIR}` an unnecessary indirection, given that `find_package()` is specified to look in "*/share/*" and does not mention `DATADIR`?

I personally do not think that it is an unnecessary indirection, as I think the idea is that with the default values everything is automatically found, but then if a user decides to modify `CMAKE_INSTALL_DATADIR` (or `CMAKE_INSTALL_LIBDIR`) then it is up to him/her to make sure that the library is correctly found. 

> I'll prepare a PR soon.

Thanks!

**Comment by drdanz** [comment]
100% in favour of this change, I've already unified the path in YARP, and I was planning to do this in YCM as well, therefore this change is very welcome! :smile: 

+1 also for `${CMAKE_INSTALL_DATADIR}` instead of `share` for `ARCH_INDEPENDENT` packages

**Comment by drdanz** [comment]
Thanks @mbeutel
