### ISSUE TITLE
Add a way to control default value of  USE_SYSTEM_<package> variables

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#322]
As is it now,  the `find_or_build_package` CMake function defines an option `USE_SYSTEM_<package>` in https://github.com/robotology/ycm/blob/597f2b1e800d8381b5e14a33274cf03850365aa4/modules/FindOrBuildPackage.cmake#L174 when a package that  needs to be built by the superbuild is found also  in the system, to let the superbuild users the option to avoid use the system package, and use instead the superbuild built version. 
Given our experience with the robotology-superbuild, it would be convenient to have a general option to change the default value of these variables from `ON` to `OFF`. This could be an option passed to the `find_or_build_package` function (but that would mean that we need to update all the `Build***.cmake` scripts, or even better a `YCM_***` CMake variable that if defined permits to specify the default value for the `USE_SYSTEM_<package>` options.

@drdanz what do you think?

**Comment by drdanz** [comment]
So just to clarify, the use case would be something like `build_or_find_package()` (i.e. build by default but, if the package is found, have an option to use the system package instead), or `build_package` (i.e. always build the package)?

**Comment by drdanz** [comment]
Related: #11

**Comment by traversaro** [comment]
> So just to clarify, the use case would be something like build_or_find_package() (i.e. build by default but, if the package is found, have an option to use the system package instead),

Exactly, I think this is the use case we are interested, to always let the user use an external package if he knows what he is doing, and he knows that the external package version is compatible (it has all the necessary options, etc etc). I do not think it is useful to remove this freedom with a `build_package` command. 

This is also meant to mitigate the recurring problems  such as https://github.com/robotology/robotology-superbuild/issues/92, and the pitfalls of using the superbuild on robot setups such as the one of iCubGenova01, in which there are multiple setups and build directories, and if you accidentally run `cmake`  on the wrong directory, going back to the previous state is quite tricky (we had this experience with @randaz81 and @xEnVrE .
