### ISSUE TITLE
Cannot download SelectLibraryConfigurations.cmake

### ISSUE THREAD

**Issue by marco-monforte** [robotology/ycm#326]
Hi guys,

I'm trying to compile YCM on my laptop with Ubuntu 18, but I get the following error:

    [  1%] Files from modules installed in CMake build directory
    [  1%] Built target modules
    [  3%] Files from find-modules installed in CMake build directory
    [  3%] Built target find-modules
    [  5%] Downloading file Modules/SelectLibraryConfigurations.cmake from CMake git repository (ref v3.15.4)
    -- Cannot download file https://raw.githubusercontent.com/Kitware/CMake/v3.15.4/Modules/SelectLibraryConfigurations.cmake
    Network problem or not existing file.
    CMake Error at /home/mmonforte/robot-code/ycm/build/cmake-next/CMakeFiles/cmake-v3.15.4.dir/ycm_download_Modules_SelectLibraryConfigurations_cmake_real.cmake:9 (file):
    file DOWNLOAD HASH mismatch

    for file: [/home/mmonforte/robot-code/ycm/build/cmake-next/CMakeFiles/cmake-v3.15.4.dir/downloads/Modules/SelectLibraryConfigurations.cmake]
      expected hash: [423e51063f8df2286ca8a693c2cbc6c3e12ec61f]
        actual hash: [da39a3ee5e6b4b0d3255bfef95601890afd80709]
             status: [1;"Unsupported protocol"].
    Retrying.

What should I do?

Thanks,
Marco

**Comment by traversaro** [comment]
>  status: [1;"Unsupported protocol"].

Which CMake are you using? This is the typical error that you get if you try to download from an https URL with a CMake compiled from source with SSL not enabled. If you want to use a custom CMake, I suggest to rely on official binaries provided by Kitware as documented in https://github.com/robotology/QA/issues/364 and https://github.com/robotology/robotology-superbuild#linux . If for any reason you want to compile CMake from source, then enable SSL support during the CMake compilation process.

**Comment by marco-monforte** [comment]
Thanks, Silvio! It solved the problem.

**Comment by drdanz** [comment]
Unfortunately, at the moment it is not possible to check if CMake was built with ssl support, therefore the error is horrible, I just opened an issue upstream

https://gitlab.kitware.com/cmake/cmake/-/issues/20507
