### ISSUE TITLE
New patch release of YCM 0.11?

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#327]
The ycm-0.11 received some improvements in the last months, including critical bugfix such as https://github.com/robotology/ycm/pull/300 and https://github.com/robotology/ycm/pull/303, without which YCM does not build. 
There is any plan to do a new patch release of YCM 0.11 (ideally after https://github.com/robotology/ycm/pull/325 is merged)? Thanks!

**Comment by drdanz** [comment]
Sure, I will take care of this in the next few days

**Comment by drdanz** [comment]
YCM 0.11.1 released, packages are on the way

**Comment by traversaro** [comment]
Thanks!
