### ISSUE TITLE
Usage with ROS/catkin packages?

### ISSUE THREAD

**Issue by martinandrovich** [robotology/ycm#379]
I was wondering whether it is possible to use `YCM` with existing ROS1/catkin packages? Instead of using `vcstool` and `catkin tools` to define (setup and build) a workspace of packages. And if, by any chance, there are some examples of doing so?

I like really the idea behind `YCM` and how it only depends on `CMake`. The paper was very well written too, so kudos!

**Comment by traversaro** [comment]
Hi @martinandrovich! I think that in general this is possible, as ROS1/catkin packages in the end are just regular CMake packages. The main challenges that I imagine you can encounter in practice are: 
* Manually convert dependencies info from `package.xml` in `Build***.cmake` files: using ROS1 or ROS2 build tools, the dependencies between packages is contained in the `package.xml` files, while if you want to use them in a YCM/CMake superbuild, you need to manually write in  `Build***.cmake` files
* It is common practice in ROS world to have a single repo that contains multiple CMake packages, each contained in its own directory. If that is the case in the projects that you want to include in the superbuild, you probably need to write a `Build***.cmake` script for each cmake package, and specify appropriately the `CONFIGURE_SOURCE_DIR` (see for example https://github.com/robotology-playground/robotology-superbuild/blob/master/cmake/Buildorocos_kdl.cmake#L10)

However, I did not try anything like that in a long time, so if you any question or if you want to report your feedback on this, feel free to do so. Note furthermore (even if this is unrelated to YCM) that w.r.t. to the past  (i.e. to when we wrote the paper) it is now possible to use tools such as colcon to build pure CMake packages, see for example https://colcon.readthedocs.io/en/released/user/quick-start.html#build-gazebo-and-the-ignition-packages .

**Comment by martinandrovich** [comment]
Hey @traversaro,

Yeah, since ROS1/catkin packages are basically CMake packages, it does seem doable - thank you for clearing things up. I actually stumbled upon `colcon` today, and am now trying to decide which tools makes the most sense to use.

**Comment by traversaro** [comment]
Hi @martinandrovich, if you think you do not have any more doubt of this, feel free to close the issue, thanks!
