### ISSUE TITLE
Error with configuration files for YCM (version 0.13.0)

### ISSUE THREAD

**Issue by Uboldi80** [robotology/ycm#392]
Hi,
today during the software installation for a new robot we had a problem with the make step:

```
Switched to a new branch 'yarp-3.6'
Branch 'yarp-3.6' set up to track remote branch 'yarp-3.6' from 'origin'.
[ 31%] No patch step for 'YARP'
[ 31%] Skipping update step for 'YARP'
[ 32%] Performing configure step for 'YARP'
Not searching for unused variables given on the command line.
loading initial cache file /usr/local/src/robot/robotology-superbuild/build/src/YARP/CMakeFiles/YCMTmp/YARP-cache-Release.cmake
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:33 (find_package):
  Could not find a configuration file for package "YCM" that is compatible
  with requested version "0.13.0".

  The following configuration files were considered but not accepted:

    /usr/share/cmake/YCM/YCMConfig.cmake, version: 0.12.2



-- Configuring incomplete, errors occurred!
See also "/usr/local/src/robot/robotology-superbuild/build/src/YARP/CMakeFiles/CMakeOutput.log".
make[2]: *** [CMakeFiles/YARP.dir/build.make:102: src/YARP/CMakeFiles/YCMStamp/YARP-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:1635: CMakeFiles/YARP.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
```

Does it depend on the new YARP versione (3.6)? How could we fix it?

Thank you!

cc @traversaro @gsisinna @drdanz

**Comment by traversaro** [comment]
Hi @Uboldi80, 

I think that somehow the iCubOS image contain a `ycm-cmake-modules` installed via deb packages (i.e. via apt). This is strange (it should be documented in https://icub-tech-iit.github.io/documentation/icub_operating_systems/icubos/installation-from-scratch, but I do not find anything).

However, I think you can proceed in two ways: 
* First, you can try to run `sudo apt update` and later `sudo apt upgrade`, to see if a new `ycm-cmake-modules` gets installed
* If this does not work, you can remove the ycm installed in the machine via `sudo apt remove ycm-cmake-modules`, and then re-configure the superbuild: if no YCM is found on the machine, the superbuild should download on its own the correct one.

**Comment by traversaro** [comment]
> This is strange (it should be documented in https://icub-tech-iit.github.io/documentation/icub_operating_systems/icubos/installation-from-scratch, but I do not find anything).

Actually I think that `ycm-cmake-modules` is a dependency of `icub-common`, for which the dependency is indeed documented: https://icub-tech-iit.github.io/documentation/icub_operating_systems/icubos/installation-from-scratch/#icub-repository-and-package .

**Comment by traversaro** [comment]
Thanks! I think we can close the issue. This seems to indicate a documentation problem, but this will be addressed in https://github.com/icub-tech-iit/documentation/issues/195 .
