### ISSUE TITLE
Automatic generation of .deb packages for new releases

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#394]
After https://github.com/robotology/ycm/releases/tag/v0.13.1 I noticed that older releases had .deb packages that I guess were generated manually. To avoid creating friction in new releases, ideally we need to:
* Understand how those packages were generated
* Generate them automatically

cc @Nicogene

**Comment by traversaro** [comment]
Probably they were generated by setting `YCM_MAINTAINER_MODE` variable (see https://github.com/robotology/ycm/blob/0454e8d38e754fc6e3a9d1baf41202b5bf80d232/CMakeLists.txt#L19) and using cpack, but I am not 100% sure.

**Comment by drdanz** [comment]
Ubuntu packages were generated using the debian scripts from https://salsa.debian.org/science-team/ycm-cmake-modules/ and uploading the source packages to the PPA https://launchpad.net/~robotology/+archive/ubuntu/test/. The generated .deb files were then downloaded manually from the PPA by @mbrunettini and uploaded in icub repository

The package was also updated in debian sid

Debian packages for other releases were generated manually on my computer, the scripts should be in the "tagging" repo in gitlab but I no longer have access... If you are interested and cannot find it, let me know, I should still have a clone...

**Comment by traversaro** [comment]
> Debian packages for other releases were generated manually on my computer, the scripts should be in the "tagging" repo in gitlab but I no longer have access...

Thanks @drdanz ! I found the relevant file, for future reference: [release-ycm.md](https://github.com/robotology/ycm/files/8729541/release-ycm.md) .

**Comment by traversaro** [comment]
No, actually this one:

### Build and upload packages on debian/ubuntu

```bash
export YCM_DEBIAN_DIR=/home/ddomenichelli/Workspace/iit/src/ycm-debian
export YCM_DEB_VERSION="${YCM_VERSION}-1"
export YCM_LATEST_UBUNTU=focal

cd ${YCM_DEBIAN_DIR}/ycm-cmake-modules
uscan
gbp import-orig ../ycm-cmake-modules_${YCM_VERSION}.orig.tar.gz
dch -v ${YCM_DEB_VERSION} "New upstream release (${YCM_VERSION})"
dch -r

git add debian/changelog
git commit -m "New upstream release (${YCM_VERSION}) and release to unstable (${YCM_DEB_VERSION})"
git tag -a -m "Debian package ${YCM_DEB_VERSION}" debian/${YCM_DEB_VERSION}

debuild -S -sa -k${GPGKEY}
dput robotology-test-${YCM_LATEST_UBUNTU} ../ycm-cmake-modules_${YCM_DEB_VERSION}_source.changes

git push origin master upstream
git push --tags origin


debuild -k${GPGKEY}
for distro in debian/buster debian/jessie debian/wheezy debian/stretch ubuntu/disco ubuntu/cosmic ubuntu/bionic ubuntu/artful ubuntu/zesty ubuntu/yakkety ubuntu/xenial; do
  package_cloud push drdanz/test/${distro} ../ycm_${YCM_DEB_VERSION}.dsc
  package_cloud push drdanz/test/${distro} ../ycm_${YCM_DEB_VERSION}_all.deb
done

```

**Comment by traversaro** [comment]
A super rough version can be done with:
~~~
git clone https://github.com/robotology/ycm
cd ycm
git checkout v0.14.0
cmake -DYCM_MAINTAINER_MODE:BOOL=ON -DCPACK_BINARY_DEB:BOOL=ON -DCPACK_DEBIAN_PACKAGE_DEPENDS="cmake" -DCPACK_DEBIAN_PACKAGE_NAME="ycm-cmake-modules" -DCPACK_DEBIAN_PACKAGE_MAINTAINER="Silvio Traversaro" .
~~~

this generates the file:

[YCM-0.14.0-all.deb.zip](https://github.com/robotology/ycm/files/8760960/YCM-0.14.0-all.deb.zip)


@Nicogene  can you check if this version is ok for you?

**Comment by Nicogene** [comment]
I managed to install ycm through `dpkg -i`
```
Selecting previously unselected package ycm-cmake-modules.
(Reading database ... 113966 files and directories currently installed.)
Preparing to unpack YCM-0.14.0-all.deb ...
Unpacking ycm-cmake-modules (0.14.0) ...
Setting up ycm-cmake-modules (0.14.0) ...
```

But then `dpkg -L` complains:
```
dpkg-query: package 'ycm-0.14.0-all.deb' is not installed
Use dpkg --contents (= dpkg-deb --contents) to list archive files contents.
```

**Comment by Nicogene** [comment]
> Which distro? On 20.04 is working fine. How are you using `dpkg -L`? `dpkg -L ycm-cmake-modules` is working fine for me.

On 22.04, `dpkg -L ycm-cmake-modules` is working fine also for me!

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/ycm/pull/410 .
