### ISSUE TITLE
Bootstrap does not accept a version parameter

### ISSUE THREAD

**Issue by drdanz** [robotology/ycm#54]
At the moment `YCMBootstrap` reads the `YCM_TAG` variable and downloads the requested tag if YCM was not found, but it does not search for a specific version, so if it finds a version minor than the required one, it will just assume that the version is correct.

It should instead do something like this:

``` cmake
find_package(YCM <version>)
if(NOT YCM_FOUND)
    ycm_bootstrap(<version>)
endif()
```

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/ycm/pull/140 ?

**Comment by drdanz** [comment]
:+1:
Closing, thanks
