### ISSUE TITLE
Unable to change CMAKE_BUILD_TYPE via subproject-edit_cache

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#66]
If I try to change the `CMAKE_BUILD_TYPE` via `subproject-edit_cache` target I am not able to save the configuration that I am setting. In particular, the following time that I build the `subproject-edit_cache` target the `CMAKE_BUILD_TYPE` option is not set, even if I had previously set it.

**Comment by drdanz** [comment]
Fixed by #188
