### ISSUE TITLE
Hash mismatch warning for IncludeUrl.cmake appears on Windows, but not on OS X/Linux

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#68]
Apparently there is an inconsistency while boostrapping YCM on the latest version of codyco-superbuild: on Windows we are getting an hash mismatch warning, on Linux/OS X no.

Linux build, without hash mismatch: 
https://travis-ci.org/robotology/codyco-superbuild/jobs/31819500

OS X build, without hash mismatch:
https://travis-ci.org/robotology/codyco-superbuild/jobs/31819502

Windows build, with hash mismatch warning:
https://ci.appveyor.com/project/traversaro/codyco-superbuild/build/1.0.20

Not a big problem, just reporting it for reference.

**Comment by drdanz** [comment]
I think this was fixed long time ago, please reopen if it is not
