### ISSUE TITLE
Make dox target

### ISSUE THREAD

**Issue by drdanz** [robotology/ycm#7]
It would be useful to have a module for adding a target to generate doxygen documentation

**Comment by claudiofantacci** [comment]
Something like [this](https://github.com/robotology/how-to-export-cpp-library/blob/master/doc/CMakeLists.txt) could be helpful in YCM?

cc @traversaro

**Comment by drdanz** [comment]
Actually the [FindDoxygen](https://cmake.org/cmake/help/v3.9/module/FindDoxygen.html) module has a command to generate the doxygen documentation since CMake 3.9, I think we could import the module in YCM...

**Comment by traversaro** [comment]
> Actually the FindDoxygen module has a command to generate the doxygen documentation since CMake 3.9, I think we could import the module in YCM...

COOOL, I had no idea.

**Comment by drdanz** [comment]
I haven't tested it though... I'm sure it will work, but I don't know how much customizable it is...

**Comment by claudiofantacci** [comment]
Oh wow this is indeed something to study!

**Comment by drdanz** [comment]
The FindDoxygen module is now imported by YCM, this can be closed
