### ISSUE TITLE
Xcode generator. (Sub)project not regenerated from the main one

### ISSUE THREAD

**Issue by francesco-romano** [robotology/ycm#74]
I noticed a strange issue with Xcode 6.1 (but I cannot say if this wasn't happening on 5.1).
I modify a CMakeLists.txt of a subproject (e.g. libraries/paramHelp), I then call `cmake` on the main build directory, but the projects are not updated (in this case I added two files).
If instead I call `cmake` directly on the subproject the Xcode project is updated.

**Comment by drdanz** [comment]
Is this still a issue?

**Comment by francesco-romano** [comment]
After 2 years of working with cmake I leaned that you have to specify the generator every time and not only the first time.  (or maybe this is a different introduced in newer versions of cmake).
I'll close this issue for now.
