### ISSUE TITLE
Amount of remote in repositories continue to grow

### ISSUE THREAD

**Issue by francesco-romano** [robotology/ycm#75]
The number of `remote` in my git repositories continue to grow:

```
Makas-Pro:motorFrictionIdentificationLib makaveli$ git remote 
origin
origin.20141112172820
origin.20141112174348
```

It is quite annoying. What are the causes of this?

**Comment by drdanz** [comment]
Sorry, I missed this...
When the remote changes (because you change the style or the address of the repository), ExternalProject does not just overwrite your origin, but makes a backup first, so that the user can recover it... How would you handle this?

**Comment by francesco-romano** [comment]
I did not remember in changes of address...
I will try to take a look at it next time. If you want to close it I will reopen it if I notice it again
