### ISSUE TITLE
YCM bootstrapping is broken

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#77]
See: https://travis-ci.org/robotology/codyco-superbuild/jobs/49588395

cc @drdanz @EnricoMingo

**Comment by drdanz** [comment]
Probably a network issue... I restarted the build.

**Comment by traversaro** [comment]
We experienced the same issue on my local computer (codyco-superbuild) and on @EnricoMingo computer (walkman-superbuild).

**Comment by traversaro** [comment]
Not it is working... @drdanz was right, probably just a network problem on the server side.

**Comment by traversaro** [comment]
Now it is not working again. If I try  to make YCM I get this error:
```
[ 11%] Downloading file Copyright.txt from CMake git repository (ref 52584050c2bb0d65b60b0164af6a28c2761d1598)
CMake Error at /home/pegua/src/ycm/build/cmake-next/CMakeFiles/cmake-52584050c2bb0d65b60b0164af6a28c2761d1598.dir/ycm_download_Copyright_txt.cmake:13 (message):
  Cannot download file
  http://cmake.org/gitweb?p=cmake.git;a=blob_plain;f=Copyright.txt;hb=52584050c2bb0d65b60b0164af6a28c2761d1598


  Network problem.
```
Possibily there are some shortage on the CMake server? Which kind of servers are checked during YCM bootstrap?

**Comment by drdanz** [comment]
Closing. Nothing I can do about... If you are worried about network issues, you can download and install YCM from outside the superbuild, but then you will have to update it manually...

**Comment by drdanz** [comment]
@traversaro YCM builld is actually not "compiling" anything, but it downloads some updated files from CMake repository and from some third party repo (iirc only FindEigen).
Once the files are downloaded the first time they are not downloaded again, unless you delete the build directory, or the address of the file is changed (i.e. if a new version is required).

Requiring the network at build time is ugly, but I don't want to include the downloaded files in the repo...

**Comment by traversaro** [comment]
You are right. However this is seriously disrupting the workflow of people using the `codyco-superbuild`. 
Until we find some time to fix issue https://github.com/robotology/ycm/issues/60 , I guess the temporary workaround we have to implement is to modify the codyco-superbuild installation guide to manually install YCM.

**Comment by traversaro** [comment]
Just to clear things:
> Once the files are downloaded the first time they are not downloaded again, unless you delete the build directory, or the address of the file is changed (i.e. if a new version is required).

That's ok and makes sense. The thing seriously disrupting is that a `cmake.org` server outage can render a user of the `codyco-superbuild` unable to compile the superbuild, as described in https://github.com/robotology/ycm/issues/60 .

**Comment by drdanz** [comment]
That's why we have offline packages for releases... see https://github.com/robotology/ycm/releases :wink:
Unfortunately we have only a 0.1.0 package for now...
