### ISSUE TITLE
Cannot configure YCM repository

### ISSUE THREAD

**Issue by paraschos** [robotology/ycm#80]
While trying to build the CoDyCo superbuild I got the following error during cmake 

-- YCM not found. Bootstrapping it.
-- Downloading YCMEPHelper.cmake
-- Downloading YCMEPHelper.cmake - SUCCESS
-- Downloading CMakeParseArguments.cmake
-- Downloading CMakeParseArguments.cmake - SUCCESS
-- Downloading ExternalProject.cmake
-- Downloading ExternalProject.cmake - SUCCESS
-- Performing download step (git clone) for 'YCM'
-- Performing update step for 'YCM'
-- Performing configure step for 'YCM'
CMake Error at build/CMakeFiles/YCMEPHelper.cmake:1285 (message):
  Cannot configure YCM repository
Call Stack (most recent call first):
  cmake/YCMBootstrap.cmake:106 (ycm_bootstrap)
  CMakeLists.txt:53 (include)

Any ideas? I am trying to build on Ubuntu 14.04 with cmake version 2.8.12.2

**Comment by drdanz** [comment]
Can you try again running ``cmake -DYCM_BOOTSTRAP_VERBOSE:BOOL=ON``?

**Comment by paraschos** [comment]
Sure, here is output

-- Downloading ExternalProject.cmake - SUCCESS
-- Performing download step (git clone) for 'YCM'
-- Avoiding repeated git clone, repository already exists
-- Performing update step for 'YCM'
From https://github.com/robotology/ycm
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
-- Performing configure step for 'YCM'
Not searching for unused variables given on the command line.
-- YCM Version: 0.2.0~20150528.17+git2eee92e (0.2.0.109)
CMake Error at /usr/share/cmake-2.8/Modules/CMakePackageConfigHelpers.cmake:164 (message):
  Unknown keywords given to CONFIGURE_PACKAGE_CONFIG_FILE():
  "INSTALL_PREFIX;/localHome/alex/icub/codyco-superbuild/build/external/YCM"
Call Stack (most recent call first):
  CMakeLists.txt:83 (configure_package_config_file)


-- Configuring incomplete, errors occurred!
See also "/localHome/alex/icub/codyco-superbuild/build/external/YCM/CMakeFiles/CMakeOutput.log".
CMake Error at build/CMakeFiles/YCMEPHelper.cmake:1285 (message):
  Cannot configure YCM repository
Call Stack (most recent call first):
  cmake/YCMBootstrap.cmake:106 (ycm_bootstrap)
  CMakeLists.txt:53 (include)


-- Configuring incomplete, errors occurred!

**Comment by drdanz** [comment]
@paraschos should be fixed now, please let me know if it is not.

**Comment by paraschos** [comment]
Cool, thx you!
