### ISSUE TITLE
YCMDefaultDirs should be deprecated

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#83]
I recently cleanup up the cmake of iDynTree, and I simplified them a bit removing all references to the variable defined by `YCMDefaultDirs`. Apparently its use is also advocated in our examples (see https://github.com/tacman-fp7/template-pkg) but what aim does this module fulfill?

**Comment by drdanz** [comment]
I'd like to get rid of the file, but unfortunately it seems to be used in several places: https://github.com/search?q=YCMDefaultDirs&type=Code

Perhaps we should deprecate it and remove it in a second moment?

**Comment by traversaro** [comment]
> Perhaps we should deprecate it and remove it in a second moment?

I agree.

**Comment by drdanz** [comment]
Renaming issue.

**Comment by drdanz** [comment]
Fixed by #234
