### ISSUE TITLE
YCM should be generic, without default YCM_BUILD_MODULES 

### ISSUE THREAD

**Issue by liesrock** [robotology/ycm#88]
In build-modules/CMakeLists.txt , in the variable YCM_BUILD_MODULES is specified a set of modules that will be build by default when we use YCM: ideally this set should be empty or at least ICUB should not be there, otherwise in the superbuild we will always have icub-main cloned and built, when making all.

**Comment by drdanz** [comment]
This variable is just a list of build modules that are installed by YCM. These are not installed automatically, but will be used when you do `find_or_build_package(FOO)`.
he idea behind this is to have all the recipes in one common place, feel free to propose new modules to move here...

**Comment by drdanz** [comment]
Closing, feel free to reopen if this answer does not satisfy you...

**Comment by liesrock** [comment]
Ok thank you for the explanation.
